### ISSUE TITLE
[Misc] Test failure: jdk/test/tools/launcher/VersionCheck.java

### ISSUE THREAD

**Issue by D-D-H** [alibaba/dragonwell8#110]
**Description**
Test failure: jdk/test/tools/launcher/VersionCheck.java

Some error logs:
Version Test: 0
Internal Strings Test: 0
Testing (-version): /home/denghui.ddh/tmptmp/jdk8u262-b10/bin/idlj
Testing (-version): /home/denghui.ddh/tmptmp/jdk8u262-b10/bin/jgroup
Testing (-version): /home/denghui.ddh/tmptmp/jdk8u262-b10/bin/java
Testing (-version): /home/denghui.ddh/tmptmp/jdk8u262-b10/bin/javah
Testing (-version): /home/denghui.ddh/tmptmp/jdk8u262-b10/bin/javac
Testing (-version): /home/denghui.ddh/tmptmp/jdk8u262-b10/bin/jdb
Testing (-version): /home/denghui.ddh/tmptmp/jdk8u262-b10/bin/jhat
Testing (-version): /home/denghui.ddh/tmptmp/jdk8u262-b10/bin/javap
----------System.err:(13/709)----------
java.lang.AssertionError: Some tests failed
        at VersionCheck.main(VersionCheck.java:227)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.lang.Thread.run(Thread.java:853)

**Steps to Reproduce**
jtreg -v:summary  dragonwell8_jdk/test/tools/launcher/VersionCheck.java

**Expected behavior**
Test passed.

**JDK version**
Alibaba Dragonwell 8.4.4

**Comment by luchsh** [comment]
@D-D-H  So what is the `clear and concise description of what the bug is.`?

**Comment by D-D-H** [comment]
> @D-D-H So what is the `clear and concise description of what the bug is.`?

Updated. Thank you!

**Comment by D-D-H** [comment]
https://github.com/alibaba/dragonwell8/issues/110 reported the same issue, but it seems to be closed without any fix.
