### ISSUE TITLE
[Bug] 使用协程，系统稳定运行8个小时后，kafka发生 invalid generation:[commit=265,broker=266(error=0)]异常，不再消费消息，同时Redis不时发生连接超时

### ISSUE THREAD

**Issue by lykxqhh** [alibaba/dragonwell8#226]
**Description**
使用8.6.6版本，线上灰度使用协程，系统稳定运行8个小时后，kafka发生 invalid generation:[commit=265,broker=266(error=0)]异常，不再消费消息，同时Redis发生连接超时，现象仅发生在dragonwell灰度实例。

JVM参数：
JVM_GC=" -XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:InitiatingHeapOccupancyPercent=40 -XX:MaxGCPauseMillis=100 -XX:+TieredCompilation -XX:CICompilerCount=4 -XX:-UseBiasedLocking -XX:+PrintGCDetails -XX:+PrintHeapAtGC -XX:+PrintTenuringDistribution -XX:+PrintGCTimeStamps -XX:+PrintGCDateStamps -XX:+PrintStringTableStatistics -XX:+PrintAdaptiveSizePolicy -XX:+PrintGCApplicationStoppedTime -XX:+PrintFlagsFinal -XX:-UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=10M -XX:+UnlockExperimentalVMOptions -XX:+UseWisp2 -Dio.netty.transport.noNative=true -Dio.netty.noUnsafe=true"

**Comment by joeyleeeeeee97** [comment]
能否提供下出现问题的jstack文件

**Comment by lykxqhh** [comment]
Coroutine [0x7fd61021b2e0] "batch-consume-thread#zcm_settle_voucher_to_clear_stage#com.nt.server.fundCheck" #833 active=816000 steal=19416 steal_fail=319 preempt=0 park=0/-1 cg=0/0 ttr=0
        at java.dyn.CoroutineSupport.unsafeSymmetricYieldTo(CoroutineSupport.java:140)
        - parking to wait for  <0x00000006f1e03f00> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at com.alibaba.wisp.engine.WispTask.switchTo(WispTask.java:335)
        at com.alibaba.wisp.engine.WispCarrier.yieldTo(WispCarrier.java:427)
        at com.alibaba.wisp.engine.WispCarrier.schedule(WispCarrier.java:265)
        at com.alibaba.wisp.engine.WispTask.parkInternal(WispTask.java:426)
        at com.alibaba.wisp.engine.WispTask.jdkPark(WispTask.java:479)
        at com.alibaba.wisp.engine.WispEngine$5.park(WispEngine.java:267)
        at sun.misc.Unsafe.park(Unsafe.java:1034)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:216)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2087)
        at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:471)
        at com.meituan.kafka.consumer.ConsumerIterator.makeNext(ConsumerIterator.scala:72)
        at com.meituan.kafka.consumer.ConsumerIterator.makeNext(ConsumerIterator.scala:36)
        at com.meituan.kafka.utils.IteratorTemplate.maybeComputeNext(IteratorTemplate.scala:66)
        at com.meituan.kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:58)
        at com.meituan.mafka.client.consumer.DefaultConsumerProcessor$MafkaStreamWorkInBatch.getMafkaMessage(DefaultConsumerProcessor.java:2121)
        at com.meituan.mafka.client.consumer.DefaultConsumerProcessor$MafkaStreamWorkInBatch.run(DefaultConsumerProcessor.java:1924)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:853)
        at com.alibaba.wisp.engine.WispTask.runOutsideWisp(WispTask.java:305)
        at com.alibaba.wisp.engine.WispTask.runCommand(WispTask.java:280)
        at com.alibaba.wisp.engine.WispTask.access$100(WispTask.java:55)
        at com.alibaba.wisp.engine.WispTask$CacheableCoroutine.run(WispTask.java:250)
        at java.dyn.CoroutineBase.startInternal(CoroutineBase.java:62)

 - Coroutine [0x7fd610242620] "ConsumerFetcherThread-conch.clearing.cost.detail_staging#com.nt.server.datacollect_set-zf-sdpt-settle-settle" #924 active=1059484 steal=33406 steal_fail=36 preempt=0 park=0/-1 cg=0/0 ttr=0
        at java.dyn.CoroutineSupport.unsafeSymmetricYieldTo(CoroutineSupport.java:140)
        at com.alibaba.wisp.engine.WispTask.switchTo(WispTask.java:335)
        at com.alibaba.wisp.engine.WispCarrier.yieldTo(WispCarrier.java:427)
        at com.alibaba.wisp.engine.WispCarrier.schedule(WispCarrier.java:265)
        at com.alibaba.wisp.engine.WispTask.parkInternal(WispTask.java:426)
        at com.alibaba.wisp.engine.WispTask.jdkPark(WispTask.java:479)
        at com.alibaba.wisp.engine.WispEngine$5.park(WispEngine.java:267)
        at com.alibaba.wisp.engine.WispEngine$5.poll(WispEngine.java:364)
        at sun.nio.ch.SocketChannelImpl.poll(SocketChannelImpl.java:992)
        - locked <0x00000006f1c18b28> (a java.lang.Object)
        at sun.nio.ch.SocketAdaptor$SocketInputStream.read(SocketAdaptor.java:217)

**Comment by lykxqhh** [comment]
- Coroutine [0x7fd61c3751a0] "ConsumerFetcherThread-com.nt.pay.settle.clear.voucherclearfinish.agent_staging#com.nt.zc.settle.settlerisk.fundCheck_" #610 active=1052451 steal=32962 steal_fail=1129 preempt=0 park=0/-1 cg=0/0 ttr=0
	at java.dyn.CoroutineSupport.unsafeSymmetricYieldTo(CoroutineSupport.java:140)
	at com.alibaba.wisp.engine.WispTask.switchTo(WispTask.java:335)
	at com.alibaba.wisp.engine.WispCarrier.yieldTo(WispCarrier.java:427)
	at com.alibaba.wisp.engine.WispCarrier.schedule(WispCarrier.java:265)
	at com.alibaba.wisp.engine.WispTask.parkInternal(WispTask.java:426)
	at com.alibaba.wisp.engine.WispTask.jdkPark(WispTask.java:479)
	at com.alibaba.wisp.engine.WispEngine$5.park(WispEngine.java:267)
	at com.alibaba.wisp.engine.WispEngine$5.poll(WispEngine.java:364)
	at sun.nio.ch.SocketChannelImpl.poll(SocketChannelImpl.java:992)
	- locked <0x00000006f18553d0> (a java.lang.Object)
	at sun.nio.ch.SocketAdaptor$SocketInputStream.read(SocketAdaptor.java:217)
	- locked <0x00000006f1855330> (a java.lang.Object)
	at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	- locked <0x00000006f1855380> (a sun.nio.ch.SocketAdaptor$SocketInputStream)
	at java.nio.channels.Channels$ReadableByteChannelImpl.read(Channels.java:385)
	- locked <0x00000006f1855340> (a java.lang.Object)
	at com.meituan.kafka.utils.Utils$.read(Utils.scala:382)
	at com.meituan.kafka.network.BoundedByteBufferReceive.readFrom(BoundedByteBufferReceive.scala:54)
	at com.meituan.kafka.network.Receive$class.readCompletely(Transmission.scala:56)
	at com.meituan.kafka.network.BoundedByteBufferReceive.readCompletely(BoundedByteBufferReceive.scala:29)
	at com.meituan.kafka.network.BlockingChannel.receive(BlockingChannel.scala:111)
	at com.meituan.kafka.consumer.SimpleConsumer.liftedTree1$1(SimpleConsumer.scala:73)
	at com.meituan.kafka.consumer.SimpleConsumer.sendRequest(SimpleConsumer.scala:70)
	- locked <0x00000006f1855688> (a java.lang.Object)
	at com.meituan.kafka.consumer.SimpleConsumer.fetch(SimpleConsumer.scala:129)
	at com.meituan.kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:98)
	at com.meituan.kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:90)
	at com.meituan.kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:60)
	at com.alibaba.wisp.engine.WispTask.runOutsideWisp(WispTask.java:305)
	at com.alibaba.wisp.engine.WispTask.runCommand(WispTask.java:280)
	at com.alibaba.wisp.engine.WispTask.access$100(WispTask.java:55)
	at com.alibaba.wisp.engine.WispTask$CacheableCoroutine.run(WispTask.java:250)
	at java.dyn.CoroutineBase.startInternal(CoroutineBase.java:62)

**Comment by lykxqhh** [comment]
Coroutine [0x7fd61021b2e0] "batch-consume-thread#zcm_settle_voucher_to_clear_stage#com.nt.server.fundCheck" #833 active=816000 steal=19416 steal_fail=319 preempt=0 park=0/-1 cg=0/0 ttr=0
        at java.dyn.CoroutineSupport.unsafeSymmetricYieldTo(CoroutineSupport.java:140)
        - parking to wait for  <0x00000006f1e03f00> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at com.alibaba.wisp.engine.WispTask.switchTo(WispTask.java:335)
        at com.alibaba.wisp.engine.WispCarrier.yieldTo(WispCarrier.java:427)
        at com.alibaba.wisp.engine.WispCarrier.schedule(WispCarrier.java:265)
        at com.alibaba.wisp.engine.WispTask.parkInternal(WispTask.java:426)
        at com.alibaba.wisp.engine.WispTask.jdkPark(WispTask.java:479)
        at com.alibaba.wisp.engine.WispEngine$5.park(WispEngine.java:267)
        at sun.misc.Unsafe.park(Unsafe.java:1034)
        at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:216)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2087)
        at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:471)
        at com.nt.kafka.consumer.ConsumerIterator.makeNext(ConsumerIterator.scala:72)
        at com.nt.kafka.consumer.ConsumerIterator.makeNext(ConsumerIterator.scala:36)
        at com.nt.kafka.utils.IteratorTemplate.maybeComputeNext(IteratorTemplate.scala:66)
        at com.nt.kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:58)
        at com.nt.mafka.client.consumer.DefaultConsumerProcessor$MafkaStreamWorkInBatch.getMafkaMessage(DefaultConsumerProcessor.java:2121)
        at com.nt.mafka.client.consumer.DefaultConsumerProcessor$MafkaStreamWorkInBatch.run(DefaultConsumerProcessor.java:1924)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:853)
        at com.alibaba.wisp.engine.WispTask.runOutsideWisp(WispTask.java:305)
        at com.alibaba.wisp.engine.WispTask.runCommand(WispTask.java:280)
        at com.alibaba.wisp.engine.WispTask.access$100(WispTask.java:55)
        at com.alibaba.wisp.engine.WispTask$CacheableCoroutine.run(WispTask.java:250)
        at java.dyn.CoroutineBase.startInternal(CoroutineBase.java:62)

 - Coroutine [0x7fd610242620] "ConsumerFetcherThread-conch.clearing.cost.detail_staging#com.nt.server.datacollect_set-zf-sdpt-settle-settle" #924 active=1059484 steal=33406 steal_fail=36 preempt=0 park=0/-1 cg=0/0 ttr=0
        at java.dyn.CoroutineSupport.unsafeSymmetricYieldTo(CoroutineSupport.java:140)
        at com.alibaba.wisp.engine.WispTask.switchTo(WispTask.java:335)
        at com.alibaba.wisp.engine.WispCarrier.yieldTo(WispCarrier.java:427)
        at com.alibaba.wisp.engine.WispCarrier.schedule(WispCarrier.java:265)
        at com.alibaba.wisp.engine.WispTask.parkInternal(WispTask.java:426)
        at com.alibaba.wisp.engine.WispTask.jdkPark(WispTask.java:479)
        at com.alibaba.wisp.engine.WispEngine$5.park(WispEngine.java:267)
        at com.alibaba.wisp.engine.WispEngine$5.poll(WispEngine.java:364)
        at sun.nio.ch.SocketChannelImpl.poll(SocketChannelImpl.java:992)
        - locked <0x00000006f1c18b28> (a java.lang.Object)
        at sun.nio.ch.SocketAdaptor$SocketInputStream.read(SocketAdaptor.java:217)

**Comment by lykxqhh** [comment]
无Blocked线程

>

**Comment by yuleil** [comment]
可以提供完整的jstack文件吗

**Comment by lykxqhh** [comment]
[jstack.txt](https://github.com/alibaba/dragonwell8/files/6314799/jstack.txt)

今早上复现的jstack

**Comment by lykxqhh** [comment]
[jstack.txt](https://github.com/alibaba/dragonwell8/files/6314810/jstack.txt)
今早上复现的jstack

**Comment by lykxqhh** [comment]
![image](https://user-images.githubusercontent.com/24647605/114805414-8b900b00-9dd5-11eb-8d19-cdc46dd1041d.png)

**Comment by joeyleeeeeee97** [comment]
@lykxqhh  您好，由于使用了com.nent.rasp.rasp.net.UnixDomainSocket 导致协程无法切换，请尝试使用
-Dcom.alibaba.wisp.threadAsWisp.black=class:com.nent.rasp.thread.CommandTask 
黑名单机制, 不将此线程转为协程

```

"Wisp-Root-Worker-2" #6 daemon prio=5 os_prio=0 tid=0x00007ff0c47d2cf0 nid=0x281 runnable [0x00007ff001940000]
   java.lang.Thread.State: RUNNABLE
	at com.nent.rasp.rasp.net.UnixDomainSocket.nativeRead(Native Method)
	at com.nent.rasp.rasp.net.UnixDomainSocket$UnixDomainSocketInputStream.read(UnixDomainSocket.java:165)
	at java.io.DataInputStream.readByte(DataInputStream.java:265)
	at com.nent.rasp.command.WireIO.read(WireIO.java:27)
	at com.nent.rasp.thread.CommandTask.run(CommandTask.java:60)
	at java.lang.Thread.run(Thread.java:853)
	at com.alibaba.wisp.engine.WispTask.runOutsideWisp(WispTask.java:305)
	at com.alibaba.wisp.engine.WispTask.runCommand(WispTask.java:280)
	at com.alibaba.wisp.engine.WispTask.access$100(WispTask.java:55)
	at com.alibaba.wisp.engine.WispTask$CacheableCoroutine.run(WispTask.java:250)
	at java.dyn.CoroutineBase.startInternal(CoroutineBase.java:62)
```

**Comment by yuleil** [comment]
更加完美的解决方案是类似go的hand off机制，可以参考[这篇文章](https://www.ardanlabs.com/blog/2018/08/scheduling-in-go-part2.html)的 **Synchronous System Calls** 小节。

**Comment by lykxqhh** [comment]
我会在今天验证一下-Dcom.alibaba.wisp.threadAsWisp.black=class:com.nent.rasp.thread.CommandTask

**Comment by lykxqhh** [comment]
-Dcom.alibaba.wisp.threadAsWisp.black=class:com.nent.rasp.thread 我可以这样配置吗，这样即是排除 class 以“com.nent.rasp.thread” 开头的所有类吗

**Comment by lykxqhh** [comment]
![image](https://user-images.githubusercontent.com/24647605/114840854-d0359980-9e09-11eb-9890-cc32c0b5b0f4.png)


-Dcom.alibaba.wisp.threadAsWisp.black=class:com.nent.rasp.thread 

这样算是成功排除掉了吗？

**Comment by yuleil** [comment]
-Dcom.alibaba.wisp.threadAsWisp.black=class:com.nent.rasp.thread.CommandTask

**Comment by lykxqhh** [comment]
private static boolean matchBlackList(Thread thread, Runnable target) {
        return Stream.concat(Stream.of(JAVA_LANG_PKG), WispConfiguration.getThreadAsWispBlacklist().stream())
                .anyMatch(s -> {
                    Class<?> clazz = (target == null ? thread : target).getClass();
                    // Java code could start a thread by passing a `target` Runnable argument
                    // or override Thread.run() method;
                    // if `target` is null, we're processing the override situation, so we need
                    // to check the thread object's class.
                    String[] sp = s.split(":");
                    if (sp.length != 2) {
                        return false;
                    }
                    switch (sp[0]) {
                        case "class":
                            return sp[1].equals(clazz.getName());
                        case "package":
                            Package pkg = clazz.getPackage();
                            String pkgName = pkg == null ? "" : pkg.getName();
                            return sp[1].equals(pkgName);
                        case "name":
                            return wildCardMatch(thread.getName(), sp[1]);
                        default:
                            return false;
                    }
                });


![image](https://user-images.githubusercontent.com/24647605/114844369-53a4ba00-9e0d-11eb-9903-bcc78ad4dda2.png)

看代码是 equals对比，但是文档，startWith 歧义很大，且不支持 class=....

**Comment by yuleil** [comment]
> 看代码是 equals对比，但是文档，startWith 歧义很大，且不支持 class=....

文档里的意思是假如配置字符串以class:开头，则根据:后面的名字来匹配类型。
举例:
class:com.nent.rasp.thread.CommandTask
表示这是一个class的配置，匹配类型为`com.nent.rasp.thread.CommandTask` 的Runnable对象。

这块功能目前触及的用户比较少，因此文档不够完善。后续我们将继续完善文档。
