### ISSUE TITLE
[Bug]当okhttp3请求执行时间超过10s，tomcat崩溃，进程重启（wisp2开启）

### ISSUE THREAD

**Issue by ScottKaiGu** [alibaba/dragonwell8#303]
**Description**
springboot， tomcat，默认异步超时时间设为10s，wisp2开启，当okhttp3请求执行时间超过10s，tomcat崩溃，进程重启

 
 

**JDK version**
OpenJDK 64-Bit Server VM (25.312-b01) for linux-amd64 JRE (1.8.0_312-b01), built on Dec  3 2021 03:44:18 by "root" with gcc 7.5.0
Memory: 4k page, physical 4194304k(4180248k free), swap 0k(0k free)
CommandLine flags: -XX:G1NewSizePercent=15 -XX:GCLogFileSize=9437184 -XX:InitialHeapSize=2411724800 -XX:MaxDirectMemorySize=1153433600 -XX:MaxGCPauseMillis=50 -XX:MaxHeapSize=2411724800 -XX:NativeMemoryTracking=summary -XX:ParallelGCThreads=8 -XX:+PrintAdaptiveSizePolicy -XX:+PrintGC -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintHeapAtGC -XX:ThreadStackSize=512 -XX:+UnlockExperimentalVMOptions -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseG1GC -XX:+UseStringDeduplication -XX:+UseWisp2 
 

**Execution environment**
 - OS and version:centos
 - CPU model:
 - Number of CPU cores:4
 - Size of physical memory:4
 - Inside Linux container yes
   - Linux container name docker
 

[ERROR 2022-03-20 13:09:39,237] [OkHttp http://preview.api.cimowifi.srv/... com.xiaocimo.cimo.apiinternal.controller.device.DeviceController] - ERROR response! {"msg":"咯屁","code":-1}  id:e585bd48-0acb-4d89-aad6-8c72ccaacae6    
[WARN  2022-03-20 13:09:39,241] [OkHttp http://preview.api.cimowifi.srv/... com.xiaocimo.cimo.apiinternal.controller.device.DeviceController] - Hit an error!   did:e585bd48-0acb-4d89-aad6-8c72ccaacae6-31834/A0Z   11148ms 
java.lang.UnsupportedOperationException: The dispatcher returned from the ServletContext does not support asynchronous dispatching
		at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:202)
		at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:178)
		at org.apache.catalina.core.AsyncContextImpl.dispatch(AsyncContextImpl.java:172)
		at org.springframework.web.context.request.async.StandardServletAsyncWebRequest.dispatch(StandardServletAsyncWebRequest.java:132)
		at org.springframework.web.context.request.async.WebAsyncManager.setConcurrentResultAndDispatch(WebAsyncManager.java:401)
		at org.springframework.web.context.request.async.WebAsyncManager.lambda$startDeferredResultProcessing$8(WebAsyncManager.java:469)
		at org.springframework.web.context.request.async.DeferredResult.setResultInternal(DeferredResult.java:267)
		at org.springframework.web.context.request.async.DeferredResult.setErrorResult(DeferredResult.java:282)
		at com.xiao.cimo.apiinternal.controller.device.DeviceController.lambda$initV2$0(DeviceController.java:461)
		at com.xiaocimo.cimo.common.service.XQDeviceRegistrationService$1.onResponse(XQDeviceRegistrationService.java:45)
		at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
		at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:853)
		at com.alibaba.wisp.engine.WispTask.runOutsideWisp(WispTask.java:299)
		at com.alibaba.wisp.engine.WispTask.runCommand(WispTask.java:274)
		at com.alibaba.wisp.engine.WispTask.access$100(WispTask.java:53)
		at com.alibaba.wisp.engine.WispTask$CacheableCoroutine.run(WispTask.java:241)
		at java.dyn.CoroutineBase.startInternal(CoroutineBase.java:62)
	 
	[INFO  2022-03-20 13:09:39,255] [scheduling-1-EventThread org.I0Itec.zkclient.ZkClient] - zookeeper state changed (Disconnected) 
	[INFO  2022-03-20 13:09:39,306] [SpringApplicationShutdownHook org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean] - Closing JPA EntityManagerFactory for persistence unit 'default' 
	[INFO  2022-03-20 13:09:39,311] [SpringApplicationShutdownHook com.zaxxer.hikari.HikariDataSource] - HikariConnPool_MYSQL - Shutdown initiated... 
	[INFO  2022-03-20 13:09:39,314] [SpringApplicationShutdownHook com.zaxxer.hikari.HikariDataSource] - HikariConnPool_MYSQL - Shutdown completed. 

	
	[INFO  2022-03-20 13:09:47,383] [main com.xiaocimo.cimo.apiinternal.cimoApiInternalApplication] - Starting cimoApiInternalApplication v0.2.5-SNAPSHOT using Java 1.8.0_312 on cimo-api-internal-prev-v46-56495dd99-2hnqr with PID 1 (/cimo-api-internal-0.2.5-SNAPSHOT.war started by root in /) 
	[INFO  2022-03-20 13:09:51,269] [main org.springframework.data.repository.config.RepositoryConfigurationDelegate] - Bootstrapping Spring Data JPA repositories in DEFAULT mode. 
	[INFO  2022-03-20 13:09:51,579] [main org.springframework.data.repository.config.RepositoryConfigurationDelegate] - Finished Spring Data repository scanning in 239 ms. Found 8 JPA repository interfaces. 
	[INFO  2022-03-20 13:09:56,271] [main org.springframework.boot.web.embedded.tomcat.TomcatWebServer] - Tomcat initialized with port(s): 9806 (http)

**Comment by MrXionGe** [comment]
看了您的启动参数，应该是没有使用“-XX:ActiveProcessorCount=n”参数来限制CPU核心数。
我特意写了一个web工程，来验证稳定性（我用的是Dragonwell11版本），如果我使用“-XX:ActiveProcessorCount=n”限制CPU的话，很快就会造成程序卡死（1核心启动之后就卡死了，4核心还能跑几分钟）。不限制核心数，目前还没遇到问题。（机器是16核心的）。

**Comment by yuleil** [comment]
> 看了您的启动参数，应该是没有使用“-XX:ActiveProcessorCount=n”参数来限制CPU核心数。 我特意写了一个web工程，来验证稳定性（我用的是Dragonwell11版本），如果我使用“-XX:ActiveProcessorCount=n”限制CPU的话，很快就会造成程序卡死（1核心启动之后就卡死了，4核心还能跑几分钟）。不限制核心数，目前还没遇到问题。（机器是16核心的）。

Wisp设计上并没有核心数的限制，从现象来看可能还是JNI阻塞了协程调度器。可以的话请提供下jstack

**Comment by MrXionGe** [comment]
@yuleil 
我理解的参数“-XX:ActiveProcessorCount=n”，应该跟go语言中的“runtime.GOMAXPROCS(n)”如出一辙。
目前还在测试中……

**Comment by MrXionGe** [comment]
@yuleil 
正巧问下您，Dragonwell17不支持Wisp2吗？我在那边提了issue，没有人回复。
https://github.com/alibaba/dragonwell17/issues/24

**Comment by ScottKaiGu** [comment]
> 看了您的启动参数，应该是没有使用“-XX:ActiveProcessorCount=n”参数来限制CPU核心数。
> 我特意写了一个web工程，来验证稳定性（我用的是Dragonwell11版本），如果我使用“-XX:ActiveProcessorCount=n”限制CPU的话，很快就会造成程序卡死（1核心启动之后就卡死了，4核心还能跑几分钟）。不限制核心数，目前还没遇到问题。（机器是16核心的）。

我这边是异步web接口，如果方法内同步执行超时，必现tomcat奔溃。

` @RequestMapping(method = RequestMethod.POST, path = "/test",
        produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
    public DeferredResult<ApiResponse<String>> testV2(...) {     DeferredResult<ApiResponse<String>> dfResult = new DeferredResult<>(9000L,
            new ApiResponse<>(ResponseCode.REQUEST_TIMED_OUT));   }`

**Comment by ScottKaiGu** [comment]
[stack-9.log.zip](https://github.com/alibaba/dragonwell8/files/8439364/stack-9.log.zip)

**Comment by ScottKaiGu** [comment]
> stack-9.log.zip

@yuleil stack 在这里
