### ISSUE TITLE
[Bug] java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by TeslaCN** [alibaba/dragonwell8#317]
**Description**

**Steps to Reproduce**
1. Prepare Apache ShardingSphere-Proxy 5.1.1
1. Start ShardingSphere-Proxy with VM options '....'
  `/home/wuweijie/.jdks/dragonwell-8.10.11/bin/java -XX:+UnlockExperimentalVMOptions -XX:+UseWisp2 -Dcom.alibaba.wisp.threadAsWisp.black=name:epollEventLoopGroup* `
1. See error

I can't understand why the following line will occur this error.

![image](https://user-images.githubusercontent.com/20503072/163769022-85bfcf46-6864-438e-9dbb-5910fe0e9777.png)

```
Exception in thread "Connection-22-ThreadExecutor" java.lang.IncompatibleClassChangeError
        at org.opengauss.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:362)
        at org.opengauss.jdbc.PgStatement.executeInternal(PgStatement.java:453)
        at org.opengauss.jdbc.PgStatement.execute(PgStatement.java:377)
        at org.opengauss.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
        at org.opengauss.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:138)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
        at org.apache.shardingsphere.proxy.backend.communication.jdbc.executor.callback.impl.ProxyPreparedStatementExecutorCallback.execute(ProxyPreparedStatementExecutorCallback.java:41)
        at org.apache.shardingsphere.proxy.backend.communication.jdbc.executor.callback.ProxyJDBCExecutorCallback.executeSQL(ProxyJDBCExecutorCallback.java:73)
        at org.apache.shardingsphere.proxy.backend.communication.jdbc.executor.callback.ProxyJDBCExecutorCallback.executeSQL(ProxyJDBCExecutorCallback.java:66)
        at org.apache.shardingsphere.proxy.backend.communication.jdbc.executor.callback.ProxyJDBCExecutorCallback.executeSQL(ProxyJDBCExecutorCallback.java:44)
        at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutorCallback.execute(JDBCExecutorCallback.java:85)
        at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutorCallback.execute(JDBCExecutorCallback.java:64)
        at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.syncExecute(ExecutorEngine.java:101)
        at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.serialExecute(ExecutorEngine.java:87)
        at org.apache.shardingsphere.infra.executor.kernel.ExecutorEngine.execute(ExecutorEngine.java:81)
        at org.apache.shardingsphere.infra.executor.sql.execute.engine.driver.jdbc.JDBCExecutor.execute(JDBCExecutor.java:65)
        at org.apache.shardingsphere.proxy.backend.communication.jdbc.executor.ProxyJDBCExecutor.execute(ProxyJDBCExecutor.java:71)
        at org.apache.shardingsphere.proxy.backend.communication.ProxySQLExecutor.useDriverToExecute(ProxySQLExecutor.java:164)
        at org.apache.shardingsphere.proxy.backend.communication.ProxySQLExecutor.execute(ProxySQLExecutor.java:125)
        at org.apache.shardingsphere.proxy.backend.communication.ProxySQLExecutor.execute(ProxySQLExecutor.java:119)
        at org.apache.shardingsphere.proxy.backend.communication.jdbc.JDBCDatabaseCommunicationEngine.execute(JDBCDatabaseCommunicationEngine.java:138)
        at org.apache.shardingsphere.proxy.frontend.postgresql.command.query.extended.JDBCPortal.bind(JDBCPortal.java:131)
        at org.apache.shardingsphere.proxy.frontend.postgresql.command.query.extended.bind.PostgreSQLComBindExecutor.execute(PostgreSQLComBindExecutor.java:54)
        at org.apache.shardingsphere.proxy.frontend.postgresql.command.query.extended.PostgreSQLAggregatedCommandExecutor.execute(PostgreSQLAggregatedCommandExecutor.java:41)
        at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.executeCommand(CommandExecutorTask.java:107)
        at org.apache.shardingsphere.proxy.frontend.command.CommandExecutorTask.run(CommandExecutorTask.java:77)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:855)
        at com.alibaba.wisp.engine.WispTask.runOutsideWisp(WispTask.java:299)
        at com.alibaba.wisp.engine.WispTask.runCommand(WispTask.java:274)
        at com.alibaba.wisp.engine.WispTask.access$100(WispTask.java:53)
        at com.alibaba.wisp.engine.WispTask$CacheableCoroutine.run(WispTask.java:241)
        at java.dyn.CoroutineBase.startInternal(CoroutineBase.java:62)
```

**Expected behavior**

No error occurs.

**JDK version**
The output of `java -version` command

```
~ ᐅ .jdks/dragonwell-8.10.11/bin/java -version
openjdk version "1.8.0_322"
OpenJDK Runtime Environment (Alibaba Dragonwell 8.10.11) (build 1.8.0_322-b01)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell 8.10.11) (build 25.322-b01, mixed mode)
```

**Execution environment**
 - OS and version: 
   `Linux wuweijie-ubuntu 5.13.0-35-generic #40~20.04.1-Ubuntu SMP Mon Mar 7 09:18:32 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
 - CPU model: 
   `AMD Ryzen 7 5700G`
 - Number of CPU cores: 
   `8C16T`
 - Size of physical memory: 
   `32GB`
 - Inside Linux container? 
   No

**Comment by lusou-zhangquan** [comment]
Seems to be associated with wisp feature, could you please take a look? @yuleil
