### ISSUE TITLE
Port JDK9 patch to improve multithreaded scalability of InetAddress cache

### ISSUE THREAD

**Issue by lusou-zhangquan** [alibaba/dragonwell8#328]
Deadlock when get address by host name, stack:
```
java.lang.Thread.State: WAITING (on object monitor)
at java.lang.Object.wait(Native Method)
at java.lang.Object.wait(Object.java:502)
at java.net.InetAddress.checkLookupTable(InetAddress.java:1393)
- locked <0x00000000804a4e78> (a java.util.HashMap)
at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1310)
at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
at java.net.InetAddress.getAllByName(InetAddress.java:1192)
at java.net.InetAddress.getAllByName(InetAddress.java:1126)
at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
```
Reason:
```
java.net.InetAddress caches results from name service lookups to improve performance and minimize load on name services. The caching mechanism was designed before java.util.concurrent existed and is using locking algorithms. This scales poorly with multithreaded hardware. Tools exist today that can improve multithreaded scalability of InetAddress cache.
```
OpenJDK bug: //bugs.openjdk.java.net/browse/JDK-8049228

commit:http://hg.openjdk.java.net/jdk9/jdk9/jdk/rev/6e125fc55925

**Comment by lusou-zhangquan** [comment]
https://github.com/openjdk/jdk8u-dev/pull/113
