### ISSUE TITLE
[Bug] 使用协程，出现接口超时

### ISSUE THREAD

**Issue by hedy2009c** [alibaba/dragonwell8#345]
使用协程，出现接口超时

**JDK version**
dragonwell 8.8.9

启动参数开启了协程并使用了全转黑名单：
-XX:+UnlockExperimentalVMOptions -XX:+UseWisp2 -Dcom.alibaba.wisp.threadAsWisp.black=class:ch.qos.logback.core.rolling.helper.Compressor$CompressionRunnable;class:com.test.zbase.service.AbstractIntercept;class:com.test.zbase.util.TSDBUtils$LogThread;class:ch.qos.logback.core.AsyncAppenderBase$Worker

看了下有些添加在黑名单里面的没有生效比如：
class:com.test.zbase.service.AbstractIntercept

堆栈信息：
[jstack.log](https://github.com/alibaba/dragonwell8/files/8890066/jstack.log)

**Comment by hedy2009c** [comment]
> 注意到黑名单里面有些规则带着'$', 启动脚本里面转义了吗? 可以ps -ef | grep java 确认下。。

ps -ef | grep java 确认了，是以下：
-XX:+UnlockExperimentalVMOptions -XX:+UseWisp2 -Dcom.alibaba.wisp.threadAsWisp.black=class:ch.qos.logback.core.rolling.helper.Compressor$CompressionRunnable;class:com.test.zbase.service.AbstractIntercept;class:com.test.zbase.util.TSDBUtils$LogThread;class:ch.qos.logback.core.AsyncAppenderBase$Worker

堆栈信息里面：ch.qos.logback.core.AsyncAppenderBase$Worker加黑名单有生效
com.test.zbase.service.AbstractIntercept 貌似没有生效：
"Wisp-Root-Worker-0" #4 daemon prio=5 os_prio=0 tid=0x00007f37d5192bd0 nid=0x268 runnable [0x00007f3685ccb000]
   java.lang.Thread.State: RUNNABLE
	at sun.misc.Unsafe.unpark0(Native Method)
	at sun.misc.Unsafe.access$100(Unsafe.java:45)
	at sun.misc.Unsafe$1.unpark0(Unsafe.java:60)
	at com.alibaba.wisp.engine.WispTask.unparkInternal(WispTask.java:454)
	at com.alibaba.wisp.engine.WispTask.jdkUnpark(WispTask.java:473)
	at com.alibaba.wisp.engine.WispEngine$5.unpark(WispEngine.java:273)
	at sun.misc.Unsafe.unpark(Unsafe.java:1001)
	at java.util.concurrent.locks.LockSupport.unpark(LockSupport.java:142)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.unparkSuccessor(AbstractQueuedSynchronizer.java:668)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1272)
	at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:457)
	at java.util.concurrent.ArrayBlockingQueue.put(ArrayBlockingQueue.java:356)
	at ch.qos.logback.core.AsyncAppenderBase.put(AsyncAppenderBase.java:160)
	at ch.qos.logback.core.AsyncAppenderBase.append(AsyncAppenderBase.java:148)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
	at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
	at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
	at ch.qos.logback.classic.Logger.filterAndLog_1(Logger.java:398)
	at ch.qos.logback.classic.Logger.info(Logger.java:583)
	at com.test.zbase.service.interceptImpl.SensitiveSentenceInterceptImpl.intercept(SensitiveSentenceInterceptImpl.java:62)
	at com.test.zbase.service.AbstractIntercept.call(AbstractIntercept.java:84)
	at com.test.zbase.service.AbstractIntercept.call(AbstractIntercept.java:25)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:853)
	at com.alibaba.wisp.engine.WispTask.runOutsideWisp(WispTask.java:295)
	at com.alibaba.wisp.engine.WispTask.runCommand(WispTask.java:270)
	at com.alibaba.wisp.engine.WispTask.access$100(WispTask.java:53)
	at com.alibaba.wisp.engine.WispTask$CacheableCoroutine.run(WispTask.java:241)
	at java.dyn.CoroutineBase.startInternal(CoroutineBase.java:62)

**Comment by joeyleeeeeee97** [comment]
@hedy2009c 
如果日志请求量很大，可以把写磁盘的黑名单掉，因为目前wisp没有对写磁盘的操作做协程调度。
但目前我看没有什么CPU密集的任务。

线程数量没必要开太多，目前有四千多个线程。你可以把线程池的策略调整下。

**Comment by hedy2009c** [comment]
好的，怎么看出来需要加黑名单的呢。

这个应该不是写文件，也跑在Wisp-Root-Worker线程上了
"Wisp-Root-Worker-0" #4 daemon prio=5 os_prio=0 tid=0x00007fa491192a30 nid=0x3caad runnable [0x00007fa30ed4d000]
   java.lang.Thread.State: RUNNABLE
	at java.util.Formatter.parse(Formatter.java:2560)
	at java.util.Formatter.format(Formatter.java:2501)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at com.test.zbase.service.InterceptCacheService.buildInterceptResultCachesKey(InterceptCacheService.java:90)
	at com.test.zbase.service.InterceptCacheService.getInterceptResultCache(InterceptCacheService.java:51)
	at com.test.zbase.service.TextAuditService.doIntercept(TextAuditService.java:158)
	at com.test.zbase.service.TextAuditService.audit(TextAuditService.java:81)
	at com.test.zbase.servant.TextAuditServantImpl$WorkRunner.call(TextAuditServantImpl.java:206)
	at com.test.zbase.servant.TextAuditServantImpl$WorkRunner.call(TextAuditServantImpl.java:190)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:853)
	at com.alibaba.wisp.engine.WispTask.runOutsideWisp(WispTask.java:295)
	at com.alibaba.wisp.engine.WispTask.runCommand(WispTask.java:270)
	at com.alibaba.wisp.engine.WispTask.access$100(WispTask.java:53)
	at com.alibaba.wisp.engine.WispTask$CacheableCoroutine.run(WispTask.java:241)
	at java.dyn.CoroutineBase.startInternal(CoroutineBase.java:62)

这个是写文件，我这样加下黑名单试试？class:ch.qos.logback.core.AsyncAppenderBase\$Worker
"Wisp-Root-Worker-4" #8 daemon prio=5 os_prio=0 tid=0x00007fa49118c8b0 nid=0x3caa9 runnable [0x00007fa41641f000]
   java.lang.Thread.State: RUNNABLE
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
	- locked <0x000000068ea811b0> (a java.io.BufferedOutputStream)
	at ch.qos.logback.core.recovery.ResilientOutputStreamBase.flush(ResilientOutputStreamBase.java:79)
	at ch.qos.logback.core.encoder.LayoutWrappingEncoder.doEncode(LayoutWrappingEncoder.java:133)
	at ch.qos.logback.core.OutputStreamAppender.writeOut(OutputStreamAppender.java:187)
	at ch.qos.logback.core.FileAppender.writeOut(FileAppender.java:279)
	at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:212)
	at ch.qos.logback.core.rolling.RollingFileAppender.subAppend(RollingFileAppender.java:235)
	at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:100)
	at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
	at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
	at ch.qos.logback.core.AsyncAppenderBase$Worker.run(AsyncAppenderBase.java:265)
	at com.alibaba.wisp.engine.WispTask.runOutsideWisp(WispTask.java:295)
	at com.alibaba.wisp.engine.WispTask.runCommand(WispTask.java:270)
	at com.alibaba.wisp.engine.WispTask.access$100(WispTask.java:53)
	at com.alibaba.wisp.engine.WispTask$CacheableCoroutine.run(WispTask.java:241)
	at java.dyn.CoroutineBase.startInternal(CoroutineBase.java:62)

**Comment by joeyleeeeeee97** [comment]
你可以试下 name:AsyncAppender-Worker-*; 这个规则会让异步日志线程不转为协程。
开四千多个线程是否有点多? 
开启协程超时，是偶尔出现超时还是整体响应时间变差了? 建议可以先调整下线程池参数。

**Comment by hedy2009c** [comment]
好的，我试试，线程数也改小看看

**Comment by hedy2009c** [comment]
name:AsyncAppender-Worker-*; 已生效。
偶尔出现超时，20分钟左右，还挺频繁的
[jstack.log](https://github.com/alibaba/dragonwell8/files/8898912/jstack.log)

最新超时对应堆栈信息：



"Wisp-Root-Worker-6" #10 daemon prio=5 os_prio=0 tid=0x00007f22e1191910 nid=0x41f04 runnable [0x00007f21ea0eb000]
   java.lang.Thread.State: RUNNABLE
	at java.lang.System.identityHashCode(Native Method)
	at java.util.IdentityHashMap.hash(IdentityHashMap.java:295)
	at java.util.IdentityHashMap.put(IdentityHashMap.java:426)
	at com.alibaba.fastjson.serializer.JSONSerializer.setContext(JSONSerializer.java:121)
	at com.alibaba.fastjson.serializer.JSONSerializer.setContext(JSONSerializer.java:109)
	at com.alibaba.fastjson.serializer.ASMSerializer_2_TextAuditRequest.write(Unknown Source)
	at com.alibaba.fastjson.serializer.JSONSerializer.write(JSONSerializer.java:285)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:758)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:696)
	at com.alibaba.fastjson.JSON.toJSONString(JSON.java:661)
	at com.test.zbase.servant.TextAuditServantImpl.audit(TextAuditServantImpl.java:69)
	at sun.reflect.GeneratedMethodAccessor88.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.test.taf.server.core.ServantHomeSkeleton.invoke(ServantHomeSkeleton.java:49)
	at com.test.taf.server.core.TafServerFilterChain.doRealInvoke(TafServerFilterChain.java:25)
	at com.test.taf.common.AbstractFilterChain.doFilter(AbstractFilterChain.java:34)
	at com.test.taf.server.core.TafServantProcessor.process(TafServantProcessor.java:158)
	at com.test.taf.net.core.nio.WorkThread.run(WorkThread.java:88)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:853)
	at com.alibaba.wisp.engine.WispTask.runOutsideWisp(WispTask.java:295)
	at com.alibaba.wisp.engine.WispTask.runCommand(WispTask.java:270)
	at com.alibaba.wisp.engine.WispTask.access$100(WispTask.java:53)
	at com.alibaba.wisp.engine.WispTask$CacheableCoroutine.run(WispTask.java:241)
	at java.dyn.CoroutineBase.startInternal(CoroutineBase.java:62)
	
	"Wisp-Root-Worker-7" #11 daemon prio=5 os_prio=0 tid=0x00007f22e11900b0 nid=0x41f03 runnable [0x00007f21cd1d5000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.NativeThread.current(Native Method)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:339)
	- locked <0x00000006fa3f5a28> (a java.lang.Object)
	- locked <0x00000006fa3f5a08> (a java.lang.Object)
	at sun.nio.ch.WispSocketImpl$WispSocketInputStream.available(WispSocketImpl.java:290)
	at java.io.BufferedInputStream.available(BufferedInputStream.java:410)
	- locked <0x00000007abdc7788> (a java.io.BufferedInputStream)
	at sun.net.www.http.ChunkedInputStream.readAheadNonBlocking(ChunkedInputStream.java:498)
	at sun.net.www.http.ChunkedInputStream.readAhead(ChunkedInputStream.java:611)
	at sun.net.www.http.ChunkedInputStream.hurry(ChunkedInputStream.java:768)
	- locked <0x00000007abdcafa0> (a sun.net.www.http.ChunkedInputStream)
	at sun.net.www.http.ChunkedInputStream.closeUnderlying(ChunkedInputStream.java:221)
	at sun.net.www.http.ChunkedInputStream.close(ChunkedInputStream.java:749)
	- locked <0x00000007abdcafa0> (a sun.net.www.http.ChunkedInputStream)
	at java.io.FilterInputStream.close(FilterInputStream.java:181)
	at sun.net.www.protocol.http.HttpURLConnection$HttpInputStream.close(HttpURLConnection.java:3527)
	at java.io.PushbackInputStream.close(PushbackInputStream.java:379)
	- locked <0x00000007abdcee20> (a java.io.PushbackInputStream)
	at com.fasterxml.jackson.core.json.UTF8StreamJsonParser._closeInput(UTF8StreamJsonParser.java:272)
	at com.fasterxml.jackson.core.base.ParserBase.close(ParserBase.java:418)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3821)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2938)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.readJavaType(AbstractJackson2HttpMessageConverter.java:235)
	at org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.read(AbstractJackson2HttpMessageConverter.java:223)
	at org.springframework.web.client.HttpMessageConverterExtractor.extractData(HttpMessageConverterExtractor.java:96)
	at org.springframework.cloud.netflix.feign.support.SpringDecoder.decode(SpringDecoder.java:59)
	at org.springframework.cloud.netflix.feign.support.ResponseEntityDecoder.decode(ResponseEntityDecoder.java:45)
	at feign.SynchronousMethodHandler.decode(SynchronousMethodHandler.java:165)
	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:133)
	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
	at feign.hystrix.HystrixInvocationHandler$1.run(HystrixInvocationHandler.java:108)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:302)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:298)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10151)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	at rx.Observable.unsafeSubscribe(Observable.java:10151)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10151)
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
	at org.springframework.cloud.sleuth.instrument.hystrix.SleuthHystrixConcurrencyStrategy$HystrixTraceCallable.call(SleuthHystrixConcurrencyStrategy.java:188)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:853)
	at com.alibaba.wisp.engine.WispTask.runOutsideWisp(WispTask.java:295)
	at com.alibaba.wisp.engine.WispTask.runCommand(WispTask.java:270)
	at com.alibaba.wisp.engine.WispTask.access$100(WispTask.java:53)
	at com.alibaba.wisp.engine.WispTask$CacheableCoroutine.run(WispTask.java:241)
	at java.dyn.CoroutineBase.startInternal(CoroutineBase.java:62)
