### ISSUE TITLE
[Bug] SimulResumerTest.java用例报错

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell8#366]
**Description**
jdk/test/com/sun/jdi/SimulResumerTest.java用例运行，大概率随机报错

**Steps to Reproduce**
```bash
cd /home/testuser/jenkins/workspace/Test_openjdk8_dragonwell_sanity.openjdk_x86-64_linux/aqa-tests/openjdk/openjdk-jdk
rm -rf tmp ; jtreg  -v:fail,error -nr -w tmp jdk/test/com/sun/jdi/SimulResumerTest.java
```

result:
```log
run args: [SimulResumerTarg]
failure: Got exception from frames(0, size - 1): java.lang.IndexOutOfBoundsException
failure: Got exception from frames(0, size - 1): java.lang.IndexOutOfBoundsException
failure: Got exception from frames(0, size - 1): java.lang.IndexOutOfBoundsException
VMDisconnectedException
java.lang.Exception: SimulResumerTest: failed; bkpts = 20000, iters = 28
        at SimulResumerTest.runTests(SimulResumerTest.java:275)
        at TestScaffold.startTests(TestScaffold.java:429)
        at SimulResumerTest.main(SimulResumerTest.java:120)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.lang.Thread.run(Thread.java:855)
```

同样的测试，使用corretto8测试pass：
```bash
cd /home/testuser/jenkins/workspace/Test_openjdk8_dragonwell_sanity.openjdk_x86-64_linux/aqa-tests/openjdk/openjdk-jdk
rm -rf tmp ; jtreg -jdk:/home/testuser/jenkins/workspace/Test_openjdk8_dragonwell_sanity.openjdk_x86-64_linux/openjdkbinary/amazon-corretto-8.342.07.3-linux-x64  -v:fail,error -nr -w tmp jdk/test/com/sun/jdi/SimulResumerTest.java
```

**JDK version**
![image](https://user-images.githubusercontent.com/24123821/181193953-6a4314f9-5a11-4b5d-8735-f7b462548fb7.png)

**Execution environment**
![image](https://user-images.githubusercontent.com/24123821/181194019-32b9652e-d30f-46e7-86b1-703242bcdba1.png)

**Comment by sendaoYan** [comment]
修改对用例修改适配
