### ISSUE TITLE
[Bug] TestClassLoaderLeak.java运行失败

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell8#369]
**Description**
jdk/test/jdk/jfr/event/oldobject/TestClassLoaderLeak.java失败

```log
java.lang.RuntimeException: Could not find class leak
        at jdk.test.lib.Asserts.fail(Asserts.java:594)
        at jdk.jfr.event.oldobject.TestClassLoaderLeak.main(TestClassLoaderLeak.java:79)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.lang.Thread.run(Thread.java:855)
```

**Steps to Reproduce**
jtreg jdk/test/jdk/jfr/event/oldobject/TestClassLoaderLeak.java

**Expected behavior**
run pass

**JDK version**
```
openjdk version "1.8.0_332"
OpenJDK Runtime Environment (Alibaba Dragonwell 8.11.12) (build 1.8.0_332-b01)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell 8.11.12) (build 25.332-b01, mixed mode)
```

**Execution environment**

![image](https://user-images.githubusercontent.com/24123821/181479054-4d49c1a3-a797-414d-88df-af1528eb02a8.png)

**Comment by sendaoYan** [comment]
合入社区patch可以解决该问题：

https://github.com/openjdk/jdk/commit/47bfc8aa9367ff852ea5d901f1fa3c6ef316913e
