### ISSUE TITLE
[Bug] GlobalPollerTest.java随机失败

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell8#371]
**Description**
jdk/test/com/alibaba/wisp/io/GlobalPollerTest.java随机失败

**Steps to Reproduce**
```bash
test=jdk/test/com/alibaba/wisp/io/GlobalPollerTest.java
dir="tmp-jtreg-"`basename $test .java` ; rm -rf $dir ; mkdir -p $dir ; time seq 500 | xargs -i -n 1 -P `nproc` bash -c "jtreg -timeoutFactor:8 -v:fail,error,time,nopass -nr -w $dir/index-{} $test &> $dir/{}.log ; grep 'Test results: passed: 1' -L $dir/{}.log"
```

```log
java.lang.RuntimeException: Expected non null reference
	at jdk.testlibrary.Asserts.error(Asserts.java:438)
	at jdk.testlibrary.Asserts.assertNotEquals(Asserts.java:322)
	at jdk.testlibrary.Asserts.assertNotNull(Asserts.java:366)
	at jdk.testlibrary.Asserts.assertNotNull(Asserts.java:355)
	at GlobalPollerTest.main(GlobalPollerTest.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:[85](https://github.com/alibaba/dragonwell8/runs/7556267675?check_suite_focus=true#step:6:86)5)
```

复现概率：大概1/10

不确定85行的fd2TaskLow对象赋值是否被执行

![image](https://user-images.githubusercontent.com/24123821/182112424-0460373d-c2b7-4289-b5e2-78035131c9c5.png)

https://github.com/alibaba/dragonwell8/runs/7556267675?check_suite_focus=true

**Expected behavior**
run pass everytime

**JDK version**
```
openjdk version "1.8.0_332"
OpenJDK Runtime Environment (Alibaba Dragonwell 8.11.12) (build 1.8.0_332-b01)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell 8.11.12) (build 25.332-b01, mixed mode)
```

**Execution environment**
![image](https://user-images.githubusercontent.com/24123821/181503076-f699e4a6-fdce-476f-a89d-60d7809b5669.png)

**Comment by sendaoYan** [comment]
复现命令：
```bash
for i in `seq 200` ; do time jtreg -v:fail,error,nopass -ignore:quiet -r jt-report-$i -w jt-work-$i -exclude:jdk/test/ProblemList.txt "jdk/test/:dragonwell_jdk_features" &> test-$i.log ; done
```

复现概率：1/20

**Comment by sendaoYan** [comment]
jdk/test/com/alibaba/wisp/thread/PreemptTest.java在linux-aarch64平台上随机失败：

失败概率：21/50

测试命令：
```bash
test=jdk/test/com/alibaba/wisp/thread/PreemptTest.java 
nproc=`nproc` ; dir="tmp-jtreg-"`basename $test .java` ; rm -rf $dir ; mkdir -p $dir ; time seq 50 | xargs -i -n 1 -P `expr $nproc / 2` bash -c "jtreg -timeoutFactor:8 -v:fail,error,time,nopass -nr -w $dir/index-{} $test &> $dir/{}.log ; grep 'Test results: passed: 1' -L $dir/{}.log"
```

```log
java.lang.RuntimeException: Expected value to be true
	at jdk.testlibrary.Asserts.error(Asserts.java:438)
	at jdk.testlibrary.Asserts.assertTrue(Asserts.java:407)
	at jdk.testlibrary.Asserts.assertTrue(Asserts.java:395)
	at PreemptTest.doTest(PreemptTest.java:51)
	at PreemptTest.main(PreemptTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:855)
```

![image](https://user-images.githubusercontent.com/24123821/182117126-8e5b6fb6-8498-40d7-a8fe-67267d597698.png)
