### ISSUE TITLE
[Bug] java/util/Currency/CurrencyTest.java用例fail

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell8#391]
**Description**
java/util/Currency/CurrencyTest.java用例fail

```
java.lang.RuntimeException: Test data and JRE's currency data are inconsistent.  test: (file: 2 data: 169), JRE: (file: 2 data: 170)
        at CheckDataVersion$1.run(CheckDataVersion.java:76)
        at java.security.AccessController.doPrivileged(Native Method)
        at CheckDataVersion.check(CheckDataVersion.java:63)
        at CurrencyTest.main(CurrencyTest.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.lang.Thread.run(Thread.java:750)
```

![image](https://user-images.githubusercontent.com/24123821/182550101-c08a34aa-0782-4bc4-8c11-edc8cb3b2e02.png)

使用上游openjdk代码仓测试用例可以pass：

![image](https://user-images.githubusercontent.com/24123821/182550290-655174fa-a0b6-4ef8-be43-c8b60a6ec135.png)

**Steps to Reproduce**
jtreg -va -nr -w tmp jdk/test/java/util/Currency/CurrencyTest.java

**Expected behavior**
run pass

**JDK version**
```
openjdk version "1.8.0_342"
OpenJDK Runtime Environment (Alibaba Dragonwell Standard Edition 8.12.13) (build 1.8.0_342-b01)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Standard Edition 8.12.13) (build 25.342-b01, mixed mode)
```

**Execution environment**
![image](https://user-images.githubusercontent.com/24123821/182549947-9bc16c0a-c85b-4a94-a648-7c4e308ba221.png)

**Comment by sendaoYan** [comment]
这个应该是这次待合入的代码，现在流程还没走完，所以还没合入
