### ISSUE TITLE
[Bug] java/util/Hashtable/DeserializedLength.java用例fail

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell8#393]
**Description**
java/util/Hashtable/DeserializedLength.java用例fail

```
STDOUT:
Results:
                 ser.  deser.
   size  load  lentgh  length       valid range ok?
------- ----- ------- ------- ----------------- ------
     10  0.15     127      43      67...    134 NOT-OK
     10  0.50      31      23      21...     42 OK
     10  0.75      15      15      14...     28 OK
     10  1.00      15      13      11...     22 OK
     10  2.50       7       7       5...     10 OK
     50  0.15     511     211     334...    668 NOT-OK
     50  0.50     127     107     101...    202 OK
     50  0.75     127      71      67...    134 OK
     50  1.00      63      55      51...    102 OK
     50  2.50      31      23      21...     42 OK
    500  0.15    4095    2103    3334...   6668 NOT-OK
    500  0.50    1023    1023    1001...   2002 OK
    500  0.75    1023     703     667...   1334 OK
    500  1.00     511     511     501...   1002 OK
    500  2.50     255     213     201...    402 OK
   5000  0.15   65535   21003   33334...  66668 NOT-OK
   5000  0.50   16383   10503   10001...  20002 OK
   5000  0.75    8191    7003    6667...  13334 OK
   5000  1.00    8191    5253    5001...  10002 OK
   5000  2.50    2047    2047    2001...   4002 OK
STDERR:
java.lang.AssertionError: Test failed.
        at DeserializedLength.main(DeserializedLength.java:107)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
        at java.lang.Thread.run(Thread.java:750)
```

**Steps to Reproduce**
rm -rf tmp ; jtreg -v:fail,error,time,nopass -nr -w tmp jdk/test/java/util/Hashtable/DeserializedLength.java

**Expected behavior**
run pass

**JDK version**
```
openjdk version "1.8.0_342"
OpenJDK Runtime Environment (Alibaba Dragonwell Standard Edition 8.12.13) (build 1.8.0_342-b01)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell Standard Edition 8.12.13) (build 25.342-b01, mixed mode)
```

**Execution environment**
![image](https://user-images.githubusercontent.com/24123821/182566500-3fd779b5-641c-425e-957c-3c5c5740d210.png)

使用上游的用例，可以运行pass：

![image](https://user-images.githubusercontent.com/24123821/182566680-bedae288-9ecc-4a07-9e13-a386edaf1124.png)

**Comment by sendaoYan** [comment]
这个应该是这次待合入的代码，现在流程还没走完，所以还没合入
