### ISSUE TITLE
SplittableRandomTest.java imtermittently timeout

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell8#428]
**Description**
jdk/test/java/util/SplittableRandom/SplittableRandomTest.java imtermittently timeout.
When the /dev/random is empty, then this testcase will run timeout

**Steps to Reproduce**
```bash
timeout 10 wc -l /dev/random
cat /proc/sys/kernel/random/entropy_avail
jtreg -timeout:0.1 -nr -w tmp -v:fail,error jdk/test/java/util/SplittableRandom/SplittableRandomTest.java
```

result:

```log
"MainThread" #26 prio=5 os_prio=0 tid=0x0000ffff94402000 nid=0xc7ad8 runnable [0x0000fffe55f3a000]
   java.lang.Thread.State: RUNNABLE
        at java.io.FileInputStream.readBytes(Native Method)
        at java.io.FileInputStream.read(FileInputStream.java:255)
        at sun.security.provider.NativePRNG$RandomIO.readFully(NativePRNG.java:424)
        at sun.security.provider.NativePRNG$RandomIO.implGenerateSeed(NativePRNG.java:441)
        - locked <0x000000008274c7e8> (a java.lang.Object)
        at sun.security.provider.NativePRNG$RandomIO.access$500(NativePRNG.java:331)
        at sun.security.provider.NativePRNG.engineGenerateSeed(NativePRNG.java:226)
        at java.security.SecureRandom.generateSeed(SecureRandom.java:533)
        at java.security.SecureRandom.getSeed(SecureRandom.java:520)
        at java.util.concurrent.ThreadLocalRandom.initialSeed(ThreadLocalRandom.java:141)
        at java.util.concurrent.ThreadLocalRandom.<clinit>(ThreadLocalRandom.java:136)
        at java.util.concurrent.ForkJoinPool.externalPush(ForkJoinPool.java:2401)
        at java.util.concurrent.ForkJoinTask.fork(ForkJoinTask.java:702)
        at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:306)
        at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:401)
        at java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:734)
        at java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
        at java.util.stream.ForEachOps$ForEachOp$OfDouble.evaluateParallel(ForEachOps.java:230)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
        at java.util.stream.DoublePipeline.forEach(DoublePipeline.java:393)
        at java.util.stream.DoublePipeline$Head.forEach(DoublePipeline.java:587)
        at SplittableRandomTest.testBoundedDoubles(SplittableRandomTest.java:488)
```

**Expected behavior**
![image](https://user-images.githubusercontent.com/24123821/199910876-d9c85262-e618-40db-98ac-4fdd8c991d86.png)

**JDK version**
![image](https://user-images.githubusercontent.com/24123821/199910993-bb112e9a-8db2-4102-9c9d-eea7587cc3f8.png)

**Execution environment**

![image](https://user-images.githubusercontent.com/24123821/199911042-3d3232a3-5ade-4ca8-bcef-21e53e3ca3f1.png)

**Comment by sendaoYan** [comment]
![image](https://user-images.githubusercontent.com/24123821/199914462-3d38ed25-3dda-45e2-841d-c3639452ae69.png)

**Comment by sendaoYan** [comment]
![image](https://user-images.githubusercontent.com/24123821/199930111-981b7e33-3a43-4d84-8a31-388635ef2f9d.png)

**Comment by sendaoYan** [comment]
http://ci.dragonwell-jdk.io/job/Test_openjdk8_dragonwell_sanity.openjdk_aarch64_linux/276/consoleFull
