### ISSUE TITLE
[Bug] 无法加载经过混淆后的jar

### ISSUE THREAD

**Issue by NeglectDream** [alibaba/dragonwell8#450]
[17:50:08] [Server thread/INFO]: [MyPet] Enabling MyPet v1.0
[17:50:08] [Server thread/ERROR]: Error occurred while enabling MyPet v1.0 (Is it up to date?)
java.lang.InternalError: Malformed class name
	at java.lang.Class.getSimpleName(Class.java:1330) ~[?:1.8.0_352]
	at java.lang.Class.isAnonymousClass(Class.java:1411) ~[?:1.8.0_352]
	at co.aikar.timings.SpigotTimings.getPluginTaskTimings(SpigotTimings.java:58) ~[%5b2%5dPaperSpigot-1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.<init>(CraftTask.java:42) ~[%5b2%5dPaperSpigot-1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.runTaskTimer(CraftScheduler.java:135) ~[%5b2%5dPaperSpigot-1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.scheduleSyncRepeatingTask(CraftScheduler.java:122) ~[%5b2%5dPaperSpigot-1.8.8.jar:git-PaperSpigot-445]
	at cn.mypet.MyPet.onEnable(p:59) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[%5b2%5dPaperSpigot-1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [%5b2%5dPaperSpigot-1.8.8.jar:git-PaperSpigot-445]
	at top.iseason.bukkit.model.PLoader.enablePlugin(PLoader.java:134) [%5B插件指定限制%5DPluginLimiter.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [%5b2%5dPaperSpigot-1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359) [%5b2%5dPaperSpigot-1.8.8.jar:git-PaperSpigot-445]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318) [%5b2%5dPaperSpigot-1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:408) [%5b2%5dPaperSpigot-1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:372) [%5b2%5dPaperSpigot-1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327) [%5b2%5dPaperSpigot-1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:267) [%5b2%5dPaperSpigot-1.8.8.jar:git-PaperSpigot-445]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:563) [%5b2%5dPaperSpigot-1.8.8.jar:git-PaperSpigot-445]
	at java.lang.Thread.run(Thread.java:855) [?:1.8.0_352]

**Comment by kuaiwei** [comment]
在openjdk8上的表现一样吗？能提供重现的步骤吗？

**Comment by kuaiwei** [comment]
能上传混淆后的jar包吗？

**Comment by sendaoYan** [comment]
> 

Error: Invalid or corrupt jarfile SuperFac.jar

![image](https://user-images.githubusercontent.com/24123821/215254075-91fcc952-82c6-495c-853c-aba134e425e3.png)

**Comment by sendaoYan** [comment]
> > > 
> > 
> > 
> > Error: Invalid or corrupt jarfile SuperFac.jar
> > ![image](https://user-images.githubusercontent.com/24123821/215254075-91fcc952-82c6-495c-853c-aba134e425e3.png)
> 
> 我使用的是MineCraft的Bukkit Server启动，是它显示的这个错误

上游的temurin jdk8 也无法解析这个jar文件。可能是这个jar文件本身有问题

![image](https://user-images.githubusercontent.com/24123821/215254159-7369ff67-07c9-4b38-b2f8-4bb973158c13.png)

**Comment by sendaoYan** [comment]
> > > > > 
> > > > 
> > > > 
> > > > Error: Invalid or corrupt jarfile SuperFac.jar
> > > > ![image](https://user-images.githubusercontent.com/24123821/215254075-91fcc952-82c6-495c-853c-aba134e425e3.png)
> > > 
> > > 
> > > 我使用的是MineCraft的Bukkit Server启动，是它显示的这个错误
> > 
> > 
> > 上游的temurin jdk8 也无法解析这个jar文件。可能是这个jar文件本身有问题
> > ![image](https://user-images.githubusercontent.com/24123821/215254159-7369ff67-07c9-4b38-b2f8-4bb973158c13.png)
> 
> 你尝试一下使用https://papermc.io(Minecraft server核心)然后放入plugins文件夹，它会显示无法启动 但是其他未加密的插件可以启动，原版的Java JDK就没这个问题

[16:55:16 ERROR]: Could not load 'plugins/SuperFac.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Unknown/missing dependency plugins: [Vault]. Please download and install these plugins to run 'SuperFac'.

![image](https://user-images.githubusercontent.com/24123821/215257043-ebb351bc-81f7-43e1-b3a4-1076877bfcd1.png)

**Comment by sendaoYan** [comment]
加载Vault插件之后，使用temurin jdk17版本启动报错java.lang.NoClassDefFoundError: com/comphenix/protocol/events/PacketListener

![image](https://user-images.githubusercontent.com/24123821/215257150-2afd832e-1a07-4c2f-9a13-7d220ea38554.png)

**Comment by sendaoYan** [comment]
这个问题，使用上游的temurin jdk8一样的报错 @3328429240
