### ISSUE TITLE
【上游问题】gc/ergonomics/TestDynamicNumberOfGCThreads.java随机crash

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell8#492]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/148381?tab=2

```log
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  ];
 stderr: [pure virtual method called
terminate called without an active exception
]
 exitValue = 134

java.lang.RuntimeException: Expected to get exit value of [0]

	at com.oracle.java.testlibrary.OutputAnalyzer.shouldHaveExitValue(OutputAnalyzer.java:362)
	at TestDynamicNumberOfGCThreads.verifyDynamicNumberOfGCThreads(TestDynamicNumberOfGCThreads.java:47)
	at TestDynamicNumberOfGCThreads.testDynamicNumberOfGCThreads(TestDynamicNumberOfGCThreads.java:57)
	at TestDynamicNumberOfGCThreads.main(TestDynamicNumberOfGCThreads.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:750)

JavaTest Message: Test threw exception: java.lang.RuntimeException: Expected to get exit value of [0]

JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: Expected to get exit value of [0]
rerun:
cd /tmp/tone/run/jtreg/jt-work/hotspot_test/gc/ergonomics/TestDynamicNumberOfGCThreads && \
DISPLAY=:7 \
HOME=/root \
LANG=en_US.UTF-8 \
PATH=/bin:/usr/bin:/usr/sbin \
CLASSPATH=/tmp/tone/run/jtreg/jt-work/hotspot_test/classes/54/gc/ergonomics:/tmp/tone/run/jtreg/jdk-repo/hotspot/test/gc/ergonomics:/tmp/tone/run/jtreg/jt-work/hotspot_test/classes/54/testlibrary:/tmp/tone/run/jtreg/jdk-repo/hotspot/test/testlibrary:/opt/java/openjdk/lib/tools.jar:/tmp/tone/run/jtreg/jtreg/lib/javatest.jar:/tmp/tone/run/jtreg/jtreg/lib/jtreg.jar \
    /opt/java/openjdk/bin/java \
        -Dtest.vm.opts='-Xmixed -ea -esa' \
        -Dtest.tool.vm.opts='-J-Xmixed -J-ea -J-esa' \
        -Dtest.compiler.opts= \
        -Dtest.java.opts= \
        -Dtest.jdk=/opt/java/openjdk \
        -Dcompile.jdk=/opt/java/openjdk \
        -Dtest.timeout.factor=4.0 \
        -Dtest.root=/tmp/tone/run/jtreg/jdk-repo/hotspot/test \
        -Dtest.name=gc/ergonomics/TestDynamicNumberOfGCThreads.java \
        -Dtest.file=/tmp/tone/run/jtreg/jdk-repo/hotspot/test/gc/ergonomics/TestDynamicNumberOfGCThreads.java \
        -Dtest.src=/tmp/tone/run/jtreg/jdk-repo/hotspot/test/gc/ergonomics \
        -Dtest.src.path=/tmp/tone/run/jtreg/jdk-repo/hotspot/test/gc/ergonomics:/tmp/tone/run/jtreg/jdk-repo/hotspot/test/testlibrary \
        -Dtest.classes=/tmp/tone/run/jtreg/jt-work/hotspot_test/classes/54/gc/ergonomics \
        -Dtest.class.path=/tmp/tone/run/jtreg/jt-work/hotspot_test/classes/54/gc/ergonomics:/tmp/tone/run/jtreg/jt-work/hotspot_test/classes/54/testlibrary \
        -Xmixed \
        -ea \
        -esa \
        com.sun.javatest.regtest.agent.MainWrapper /tmp/tone/run/jtreg/jt-work/hotspot_test/gc/ergonomics/TestDynamicNumberOfGCThreads.d/main.0.jta

TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected to get exit value of [0]
```

**Comment by sendaoYan** [comment]
dragonwell8 必现，还需要进一步确认
