### ISSUE TITLE
【上游问题】java/nio/file/Files/probeContentType/ForceLoad.java报错

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell8#495]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/148560

```log
STDERR:
java.util.ServiceConfigurationError: java.nio.file.spi.FileTypeDetector: Provider SimpleFileTypeDetector not found
	at java.util.ServiceLoader.fail(ServiceLoader.java:239)
	at java.util.ServiceLoader.access$300(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:372)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at java.nio.file.Files$FileTypeDetectors$2.run(Files.java:1558)
	at java.nio.file.Files$FileTypeDetectors$2.run(Files.java:1553)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.nio.file.Files$FileTypeDetectors.loadInstalledDetectors(Files.java:1553)
	at java.nio.file.Files$FileTypeDetectors.<clinit>(Files.java:1539)
	at java.nio.file.Files.probeContentType(Files.java:1617)
	at ForceLoad.main(ForceLoad.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:855)
```

**Comment by sendaoYan** [comment]
java/nio/file/Files/probeContentType/ParallelProbes.java可能是类似问题

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix-compiler/codereview/18847273
