### ISSUE TITLE
-Xcomp选项运行com/alibaba/wisp/ParkTest.java随机报错

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell8#497]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/148357?tab=1

```log
java.util.concurrent.ExecutionException: java.lang.Error: error test unpark by other thread
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:206)
	at ParkTest.main(ParkTest.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:855)
	at com.alibaba.wisp.engine.WispTask.runOutsideWisp(WispTask.java:299)
	at com.alibaba.wisp.engine.WispTask.runCommand(WispTask.java:274)
	at com.alibaba.wisp.engine.WispTask.access$100(WispTask.java:53)
	at com.alibaba.wisp.engine.WispTask$CacheableCoroutine.run(WispTask.java:241)
	at java.dyn.CoroutineBase.startInternal(CoroutineBase.java:62)
Caused by: java.lang.Error: error test unpark by other thread
	at ParkTest.lambda$main$0(ParkTest.java:56)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 5 more
```

replay command:
```bash
test=jdk/test/com/alibaba/wisp/ParkTest.java
nproc=`nproc` ; dir="tmp-jtreg-"`basename $test .java` ; rm -rf $dir ; mkdir -p $dir ; time seq 50 | xargs -i -n 1 -P $nproc bash -c "jtreg -Xcomp -ea -esa -timeoutFactor:4 -v:fail,error,time,nopass -nr -w $dir/index-{} $test &> $dir/{}.log ; grep 'Test results: passed: 1' -L $dir/{}.log"
```

[9.log](https://github.com/alibaba/dragonwell8/files/10811544/9.log)
[98.log](https://github.com/alibaba/dragonwell8/files/10811545/98.log)
[97.log](https://github.com/alibaba/dragonwell8/files/10811546/97.log)
[96.log](https://github.com/alibaba/dragonwell8/files/10811547/96.log)
[95.log](https://github.com/alibaba/dragonwell8/files/10811548/95.log)
[94.log](https://github.com/alibaba/dragonwell8/files/10811549/94.log)
[93.log](https://github.com/alibaba/dragonwell8/files/10811550/93.log)
[92.log](https://github.com/alibaba/dragonwell8/files/10811552/92.log)
[91.log](https://github.com/alibaba/dragonwell8/files/10811553/91.log)
[90.log](https://github.com/alibaba/dragonwell8/files/10811554/90.log)
[8.log](https://github.com/alibaba/dragonwell8/files/10811555/8.log)

**Comment by sendaoYan** [comment]
-Xmixed也会报错：

https://tone.aliyun-inc.com/ws/xesljfzh/test_result/149074

**Comment by sendaoYan** [comment]
com/alibaba/wisp/bug/LazySetUnparkTest.java

**Comment by sendaoYan** [comment]
com/alibaba/wisp/thread/ThrowErrorTest.java


https://tone.aliyun-inc.com/ws/xesljfzh/test_result/158833?tab=1


```log
ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected value to be true
REASON: User specified action: run main/othervm -XX:+UnlockExperimentalVMOptions -XX:+EnableCoroutine -Dcom.alibaba.wisp.transparentWispSwitch=true ThrowErrorTest 
TIME:   4.703 seconds
messages:
command: main -XX:+UnlockExperimentalVMOptions -XX:+EnableCoroutine -Dcom.alibaba.wisp.transparentWispSwitch=true ThrowErrorTest
reason: User specified action: run main/othervm -XX:+UnlockExperimentalVMOptions -XX:+EnableCoroutine -Dcom.alibaba.wisp.transparentWispSwitch=true ThrowErrorTest 
Mode: othervm [/othervm specified]
elapsed time (seconds): 4.703
configuration:
STDOUT:
STDERR:
Exception in thread "execute task" java.lang.Error
	at ThrowErrorTest.lambda$main$0(ThrowErrorTest.java:37)
	at com.alibaba.wisp.engine.WispTask.runOutsideWisp(WispTask.java:299)
	at com.alibaba.wisp.engine.WispTask.runCommand(WispTask.java:274)
	at com.alibaba.wisp.engine.WispTask.access$100(WispTask.java:53)
	at com.alibaba.wisp.engine.WispTask$CacheableCoroutine.run(WispTask.java:241)
	at java.dyn.CoroutineBase.startInternal(CoroutineBase.java:62)
java.lang.RuntimeException: Expected value to be true
	at jdk.testlibrary.Asserts.error(Asserts.java:438)
	at jdk.testlibrary.Asserts.assertTrue(Asserts.java:407)
	at jdk.testlibrary.Asserts.assertTrue(Asserts.java:395)
	at ThrowErrorTest.main(ThrowErrorTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:82)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:879)

JavaTest Message: Test threw exception: java.lang.RuntimeException: Expected value to be true
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: Expected value to be true
rerun:
cd /tmp/tone/run/jtreg/jt-work/jdk_test/com/alibaba/wisp/thread/ThrowErrorTest && \
DISPLAY=:7 \
HOME=/home/testUserForTone \
LANG=C \
LC_CTYPE=C.UTF-8 \
PATH=/bin:/usr/bin:/usr/sbin \
CLASSPATH=/tmp/tone/run/jtreg/jt-work/jdk_test/classes/125/com/alibaba/wisp/thread:/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp/thread:/tmp/tone/run/jtreg/jt-work/jdk_test/classes/125/lib/testlibrary:/tmp/tone/run/jtreg/jdk-repo/jdk/test/lib/testlibrary:/tmp/tone/run/jtreg/binary-download/jdk8u362-b747/lib/tools.jar:/tmp/tone/run/jtreg/jtreg/lib/javatest.jar:/tmp/tone/run/jtreg/jtreg/lib/jtreg.jar \
    /tmp/tone/run/jtreg/binary-download/jdk8u362-b747/bin/java \
        -Dtest.vm.opts='-Djdk.lang.processReaperUseDefaultStackSize=true -Xcomp -ea -esa' \
        -Dtest.tool.vm.opts='-J-Djdk.lang.processReaperUseDefaultStackSize=true -J-Xcomp -J-ea -J-esa' \
        -Dtest.compiler.opts= \
        -Dtest.java.opts= \
        -Dtest.jdk=/tmp/tone/run/jtreg/binary-download/jdk8u362-b747 \
        -Dcompile.jdk=/tmp/tone/run/jtreg/binary-download/jdk8u362-b747 \
        -Dtest.timeout.factor=4.0 \
        -Dtest.root=/tmp/tone/run/jtreg/jdk-repo/jdk/test \
        -Dtest.name=com/alibaba/wisp/thread/ThrowErrorTest.java \
        -Dtest.file=/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp/thread/ThrowErrorTest.java \
        -Dtest.src=/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp/thread \
        -Dtest.src.path=/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp/thread:/tmp/tone/run/jtreg/jdk-repo/jdk/test/lib/testlibrary \
        -Dtest.classes=/tmp/tone/run/jtreg/jt-work/jdk_test/classes/125/com/alibaba/wisp/thread \
        -Dtest.class.path=/tmp/tone/run/jtreg/jt-work/jdk_test/classes/125/com/alibaba/wisp/thread:/tmp/tone/run/jtreg/jt-work/jdk_test/classes/125/lib/testlibrary \
        -Djdk.lang.processReaperUseDefaultStackSize=true \
        -Xcomp \
        -ea \
        -esa \
        -XX:+UnlockExperimentalVMOptions \
        -XX:+EnableCoroutine \
        -Dcom.alibaba.wisp.transparentWispSwitch=true \
        com.sun.javatest.regtest.agent.MainWrapper /tmp/tone/run/jtreg/jt-work/jdk_test/com/alibaba/wisp/thread/ThrowErrorTest.d/main.0.jta
```

**Comment by sendaoYan** [comment]
> com/alibaba/wisp2/MassiveIOTest.java
-Xcomp:
https://github.com/dragonwell-releng/dragonwell-adoptium/issues/105
