### ISSUE TITLE
【上游问题】sun/security/lib/cacerts/VerifyCACerts.java失败

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell8#501]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/148358?tab=1

```
ERROR: cert " ,c=hk,o=hongkong post,cn=hongkong post root ca 1" expiry "Mon May 15 12:52:29 CST 2023" will expire within 90 days
ERROR: cert " ,c=tr,l=ankara,o=e-tu\xc4\x9fra ebg bili\xc5\x9fim teknolojileri ve hizmetleri a.\xc5\x9e.,ou=e-tugra sertifikasyon merkezi,cn=e-tugra certification authority" expiry "Fri Mar 03 20:09:48 CST 2023" will expire within 90 days
ERROR: cert is expired
ERROR: cert " ,c=nl,o=staat der nederlanden,cn=staat der nederlanden ev root ca" expiry "Thu Dec 08 19:10:28 CST 2022" will expire within 90 days
java.lang.Exception: At least one cacert test failed
	at VerifyCACerts.main(VerifyCACerts.java:357)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:855)
```

**Comment by sendaoYan** [comment]
sun/security/ssl/X509TrustManagerImpl/Symantec/Distrust.java

**Comment by sendaoYan** [comment]
https://code.alibaba-inc.com/os-quality/tone-matrix-compiler/codereview/18847845
