### ISSUE TITLE
[Bug] Wisp-Root-Worker-0 cpu占用100%

### ISSUE THREAD

**Issue by halfciga** [alibaba/dragonwell8#515]
[1.txt](https://github.com/alibaba/dragonwell8/files/10904378/1.txt)
![1](https://user-images.githubusercontent.com/25999987/223296958-1bf4e5bf-9d9e-4a06-b130-285fe0246e21.png)
在容器环境中部署项目，在选择1核资源的情况下，Wisp-Root-Worker-0占用cpu 100%，从stack上看是在kafkaclient的poll方法中。如果选择2核或者以上的资源不会出现此问题。

**Comment by halfciga** [comment]
对比了一下正常的stack，发现出现问题的场景中多这样一个Coroutine 

 - Coroutine [0x7f9064011890] "Wisp-Root-Worker-0" #2 active=38908 steal=0 steal_fail=0 preempt=0 park=0/0 containerId=0 cg=0/0 ttr=0
	at java.dyn.CoroutineSupport.unsafeSymmetricYieldTo(CoroutineSupport.java:140)
	at com.alibaba.wisp.engine.WispTask.switchTo(WispTask.java:329)
	at com.alibaba.wisp.engine.WispCarrier.yieldTo(WispCarrier.java:436)
	at com.alibaba.wisp.engine.WispCarrier.access$300(WispCarrier.java:42)
	at com.alibaba.wisp.engine.WispCarrier$1.run(WispCarrier.java:354)
	at com.alibaba.wisp.engine.WispScheduler.doExec(WispScheduler.java:536)
	at com.alibaba.wisp.engine.WispScheduler.access$600(WispScheduler.java:43)
	at com.alibaba.wisp.engine.WispScheduler$Worker.runCarrier(WispScheduler.java:161)
	at com.alibaba.wisp.engine.WispScheduler$Worker.run(WispScheduler.java:141)
	at java.lang.Thread.run(Thread.java:855)

正常的堆栈下没有出现

**Comment by halfciga** [comment]
@yuleil @zhengxiaolinX 两位能帮忙看看这个问题吗？
