### ISSUE TITLE
【自研】-Xcomp -XX:TieredStopAtLevel=1选项com/alibaba/wisp/timer/SleepRPCTest.java随机失败

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell8#518]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/152767?tab=1

```log
ACTION: build -- Passed. All files up to date
REASON: Named class compiled on demand
TIME:   0.0 seconds
messages:
command: build SleepRPCTest
reason: Named class compiled on demand
elapsed time (seconds): 0.0

ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected value to be true
REASON: User specified action: run main/othervm -XX:+UnlockExperimentalVMOptions -XX:+EnableCoroutine -XX:+UseWispMonitor -Dcom.alibaba.wisp.transparentWispSwitch=true -Dcom.alibaba.wisp.highPrecisionTimer=true SleepRPCTest 
TIME:   2.553 seconds
messages:
command: main -XX:+UnlockExperimentalVMOptions -XX:+EnableCoroutine -XX:+UseWispMonitor -Dcom.alibaba.wisp.transparentWispSwitch=true -Dcom.alibaba.wisp.highPrecisionTimer=true SleepRPCTest
reason: User specified action: run main/othervm -XX:+UnlockExperimentalVMOptions -XX:+EnableCoroutine -XX:+UseWispMonitor -Dcom.alibaba.wisp.transparentWispSwitch=true -Dcom.alibaba.wisp.highPrecisionTimer=true SleepRPCTest 
Mode: othervm [/othervm specified]
elapsed time (seconds): 2.553
configuration:
STDOUT:
STDERR:
java.lang.RuntimeException: Expected value to be true
	at jdk.testlibrary.Asserts.error(Asserts.java:438)
	at jdk.testlibrary.Asserts.assertTrue(Asserts.java:407)
	at jdk.testlibrary.Asserts.assertTrue(Asserts.java:395)
	at SleepRPCTest.main(SleepRPCTest.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:855)

JavaTest Message: Test threw exception: java.lang.RuntimeException: Expected value to be true
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: Expected value to be true
rerun:
cd /tmp/tone/run/jtreg/jt-work/jdk_test/com/alibaba/wisp/timer/SleepRPCTest && \
DISPLAY=:7 \
HOME=/root \
LANG=en_US.UTF-8 \
PATH=/bin:/usr/bin:/usr/sbin \
CLASSPATH=/tmp/tone/run/jtreg/jt-work/jdk_test/classes/36/com/alibaba/wisp/timer:/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp/timer:/tmp/tone/run/jtreg/jt-work/jdk_test/classes/36/lib/testlibrary:/tmp/tone/run/jtreg/jdk-repo/jdk/test/lib/testlibrary:/opt/java/openjdk/lib/tools.jar:/tmp/tone/run/jtreg/jtreg/lib/javatest.jar:/tmp/tone/run/jtreg/jtreg/lib/jtreg.jar \
    /opt/java/openjdk/bin/java \
        -Dtest.vm.opts='-Xcomp -XX:TieredStopAtLevel=1 -ea -esa' \
        -Dtest.tool.vm.opts='-J-Xcomp -J-XX:TieredStopAtLevel=1 -J-ea -J-esa' \
        -Dtest.compiler.opts= \
        -Dtest.java.opts= \
        -Dtest.jdk=/opt/java/openjdk \
        -Dcompile.jdk=/opt/java/openjdk \
        -Dtest.timeout.factor=4.0 \
        -Dtest.root=/tmp/tone/run/jtreg/jdk-repo/jdk/test \
        -Dtest.name=com/alibaba/wisp/timer/SleepRPCTest.java \
        -Dtest.file=/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp/timer/SleepRPCTest.java \
        -Dtest.src=/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp/timer \
        -Dtest.src.path=/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp/timer:/tmp/tone/run/jtreg/jdk-repo/jdk/test/lib/testlibrary \
        -Dtest.classes=/tmp/tone/run/jtreg/jt-work/jdk_test/classes/36/com/alibaba/wisp/timer \
        -Dtest.class.path=/tmp/tone/run/jtreg/jt-work/jdk_test/classes/36/com/alibaba/wisp/timer:/tmp/tone/run/jtreg/jt-work/jdk_test/classes/36/lib/testlibrary \
        -Xcomp \
        -XX:TieredStopAtLevel=1 \
        -ea \
        -esa \
        -XX:+UnlockExperimentalVMOptions \
        -XX:+EnableCoroutine \
        -XX:+UseWispMonitor \
        -Dcom.alibaba.wisp.transparentWispSwitch=true \
        -Dcom.alibaba.wisp.highPrecisionTimer=true \
        com.sun.javatest.regtest.agent.MainWrapper /tmp/tone/run/jtreg/jt-work/jdk_test/com/alibaba/wisp/timer/SleepRPCTest.d/main.1.jta

TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected value to be true
```

**Comment by sendaoYan** [comment]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/153922?tab=2

com/alibaba/wisp/LoadClassInnerWispGuard.java

```log
ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: [Loaded java.util.concurrent.locks.LockSupport from /opt/java/openjdk/jre/lib/rt.jar] wisp class loaded during runtime
REASON: User specified action: run main LoadClassInnerWispGuard 
TIME:   3.738 seconds
messages:
command: main LoadClassInnerWispGuard
reason: User specified action: run main LoadClassInnerWispGuard 
Mode: othervm
elapsed time (seconds): 3.738
configuration:
STDOUT:
Command line: [/opt/java/openjdk/bin/java -XX:+UnlockExperimentalVMOptions -XX:+UseWisp2 -Dcom.alibaba.wisp.allThreadAsWisp=false -verbose:class -cp /tmp/tone/run/jtreg/jt-work/jdk_test/classes/42/com/alibaba/wisp:/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp:/tmp/tone/run/jtreg/jt-work/jdk_test/classes/42/lib/testlibrary:/tmp/tone/run/jtreg/jdk-repo/jdk/test/lib/testlibrary:/opt/java/openjdk/lib/tools.jar:/tmp/tone/run/jtreg/jtreg/lib/javatest.jar:/tmp/tone/run/jtreg/jtreg/lib/jtreg.jar LoadClassInnerWispGuard 1 ]
STDERR:
java.lang.RuntimeException: [Loaded java.util.concurrent.locks.LockSupport from /opt/java/openjdk/jre/lib/rt.jar]
wisp class loaded during runtime
	at jdk.testlibrary.Asserts.error(Asserts.java:438)
	at jdk.testlibrary.Asserts.fail(Asserts.java:424)
	at LoadClassInnerWispGuard.driver(LoadClassInnerWispGuard.java:75)
	at LoadClassInnerWispGuard.main(LoadClassInnerWispGuard.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:855)

JavaTest Message: Test threw exception: java.lang.RuntimeException: [Loaded java.util.concurrent.locks.LockSupport from /opt/java/openjdk/jre/lib/rt.jar]
wisp class loaded during runtime
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: [Loaded java.util.concurrent.locks.LockSupport from /opt/java/openjdk/jre/lib/rt.jar] wisp class loaded during runtime
rerun:
cd /tmp/tone/run/jtreg/jt-work/jdk_test/com/alibaba/wisp/LoadClassInnerWispGuard && \
DISPLAY=:7 \
HOME=/root \
LANG=en_US.UTF-8 \
PATH=/bin:/usr/bin:/usr/sbin \
CLASSPATH=/tmp/tone/run/jtreg/jt-work/jdk_test/classes/42/com/alibaba/wisp:/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp:/tmp/tone/run/jtreg/jt-work/jdk_test/classes/42/lib/testlibrary:/tmp/tone/run/jtreg/jdk-repo/jdk/test/lib/testlibrary:/opt/java/openjdk/lib/tools.jar:/tmp/tone/run/jtreg/jtreg/lib/javatest.jar:/tmp/tone/run/jtreg/jtreg/lib/jtreg.jar \
    /opt/java/openjdk/bin/java \
        -Dtest.vm.opts='-Xcomp -XX:TieredStopAtLevel=1 -ea -esa' \
        -Dtest.tool.vm.opts='-J-Xcomp -J-XX:TieredStopAtLevel=1 -J-ea -J-esa' \
        -Dtest.compiler.opts= \
        -Dtest.java.opts= \
        -Dtest.jdk=/opt/java/openjdk \
        -Dcompile.jdk=/opt/java/openjdk \
        -Dtest.timeout.factor=4.0 \
        -Dtest.root=/tmp/tone/run/jtreg/jdk-repo/jdk/test \
        -Dtest.name=com/alibaba/wisp/LoadClassInnerWispGuard.java \
        -Dtest.file=/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp/LoadClassInnerWispGuard.java \
        -Dtest.src=/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp \
        -Dtest.src.path=/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp:/tmp/tone/run/jtreg/jdk-repo/jdk/test/lib/testlibrary \
        -Dtest.classes=/tmp/tone/run/jtreg/jt-work/jdk_test/classes/42/com/alibaba/wisp \
        -Dtest.class.path=/tmp/tone/run/jtreg/jt-work/jdk_test/classes/42/com/alibaba/wisp:/tmp/tone/run/jtreg/jt-work/jdk_test/classes/42/lib/testlibrary \
        -Xcomp \
        -XX:TieredStopAtLevel=1 \
        -ea \
        -esa \
        com.sun.javatest.regtest.agent.MainWrapper /tmp/tone/run/jtreg/jt-work/jdk_test/com/alibaba/wisp/LoadClassInnerWispGuard.d/main.0.jta

```

**Comment by sendaoYan** [comment]
runtime/coroutine/TestMemLeak.java

https://tone.aliyun-inc.com/ws/xesljfzh/test_result/154143?tab=2

```log
ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.Error: thread coroutine mem leak
REASON: User specified action: run main/othervm -XX:+UnlockExperimentalVMOptions -XX:+EnableCoroutine -Dcom.alibaba.wisp.version=2 -Xmx10m -Xms10m TestMemLeak 
TIME:   18.388 seconds
messages:
command: main -XX:+UnlockExperimentalVMOptions -XX:+EnableCoroutine -Dcom.alibaba.wisp.version=2 -Xmx10m -Xms10m TestMemLeak
reason: User specified action: run main/othervm -XX:+UnlockExperimentalVMOptions -XX:+EnableCoroutine -Dcom.alibaba.wisp.version=2 -Xmx10m -Xms10m TestMemLeak 
Mode: othervm [/othervm specified]
elapsed time (seconds): 18.388
configuration:
STDOUT:
56116
58168
STDERR:
java.lang.Error: thread coroutine mem leak
	at TestMemLeak.testThreadCoroutineLeak(TestMemLeak.java:46)
	at TestMemLeak.main(TestMemLeak.java:16)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.base/java.lang.Thread.run(Thread.java:955)

JavaTest Message: Test threw exception: java.lang.Error: thread coroutine mem leak
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.Error: thread coroutine mem leak
rerun:
cd /tmp/tone/run/jtreg/jt-work/hotspot_jtreg/runtime/coroutine/TestMemLeak && \
DISPLAY=:7 \
HOME=/root \
LANG=en_US.UTF-8 \
PATH=/bin:/usr/bin:/usr/sbin \
TEST_IMAGE_DIR=/tmp/tone/run/jtreg/test-images \
CLASSPATH=/tmp/tone/run/jtreg/jt-work/hotspot_jtreg/classes/28/runtime/coroutine/TestMemLeak.d:/tmp/tone/run/jtreg/jdk-repo/test/hotspot/jtreg/runtime/coroutine:/tmp/tone/run/jtreg/jtreg/lib/javatest.jar:/tmp/tone/run/jtreg/jtreg/lib/jtreg.jar \
    /opt/java/openjdk/bin/java \
        -Dtest.vm.opts='-Xcomp -XX:TieredStopAtLevel=1 -ea -esa' \
        -Dtest.tool.vm.opts='-J-Xcomp -J-XX:TieredStopAtLevel=1 -J-ea -J-esa' \
        -Dtest.compiler.opts= \
        -Dtest.java.opts= \
        -Dtest.jdk=/opt/java/openjdk \
        -Dcompile.jdk=/opt/java/openjdk \
        -Dtest.timeout.factor=4.0 \
        -Dtest.nativepath=/tmp/tone/run/jtreg/test-images/hotspot/jtreg/native \
        -Dtest.root=/tmp/tone/run/jtreg/jdk-repo/test/hotspot/jtreg \
        -Dtest.name=runtime/coroutine/TestMemLeak.java \
        -Dtest.file=/tmp/tone/run/jtreg/jdk-repo/test/hotspot/jtreg/runtime/coroutine/TestMemLeak.java \
        -Dtest.src=/tmp/tone/run/jtreg/jdk-repo/test/hotspot/jtreg/runtime/coroutine \
        -Dtest.src.path=/tmp/tone/run/jtreg/jdk-repo/test/hotspot/jtreg/runtime/coroutine \
        -Dtest.classes=/tmp/tone/run/jtreg/jt-work/hotspot_jtreg/classes/28/runtime/coroutine/TestMemLeak.d \
        -Dtest.class.path=/tmp/tone/run/jtreg/jt-work/hotspot_jtreg/classes/28/runtime/coroutine/TestMemLeak.d \
        -Xcomp \
        -XX:TieredStopAtLevel=1 \
        -ea \
        -esa \
        -Djava.library.path=/tmp/tone/run/jtreg/test-images/hotspot/jtreg/native \
        -XX:+UnlockExperimentalVMOptions \
        -XX:+EnableCoroutine \
        -Dcom.alibaba.wisp.version=2 \
        -Xmx10m \
        -Xms10m \
        com.sun.javatest.regtest.agent.MainWrapper /tmp/tone/run/jtreg/jt-work/hotspot_jtreg/runtime/coroutine/TestMemLeak.d/main.0.jta

```

**Comment by sendaoYan** [comment]
com/alibaba/wisp2/ReleaseWispTaskTest.java

https://tone.aliyun-inc.com/ws/xesljfzh/test_result/154915?tab=2

```log
ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected value to be true
REASON: User specified action: run main/othervm -XX:+UnlockExperimentalVMOptions -XX:+UseWisp2 -XX:ActiveProcessorCount=2 ReleaseWispTaskTest 
TIME:   2.122 seconds
messages:
command: main -XX:+UnlockExperimentalVMOptions -XX:+UseWisp2 -XX:ActiveProcessorCount=2 ReleaseWispTaskTest
reason: User specified action: run main/othervm -XX:+UnlockExperimentalVMOptions -XX:+UseWisp2 -XX:ActiveProcessorCount=2 ReleaseWispTaskTest 
Mode: othervm [/othervm specified]
elapsed time (seconds): 2.122
configuration:
STDOUT:
STDERR:
java.lang.RuntimeException: Expected value to be true
	at jdk.testlibrary.Asserts.error(Asserts.java:438)
	at jdk.testlibrary.Asserts.assertTrue(Asserts.java:407)
	at jdk.testlibrary.Asserts.assertTrue(Asserts.java:395)
	at ReleaseWispTaskTest.main(ReleaseWispTaskTest.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:82)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:879)
	at com.alibaba.wisp.engine.WispTask.runOutsideWisp(WispTask.java:299)
	at com.alibaba.wisp.engine.WispTask.runCommand(WispTask.java:274)
	at com.alibaba.wisp.engine.WispTask.access$100(WispTask.java:53)
	at com.alibaba.wisp.engine.WispTask$CacheableCoroutine.run(WispTask.java:241)
	at java.dyn.CoroutineBase.startInternal(CoroutineBase.java:62)

JavaTest Message: Test threw exception: java.lang.RuntimeException: Expected value to be true
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: Expected value to be true
rerun:
cd /tmp/tone/run/jtreg/jt-work/jdk_test/com/alibaba/wisp2/ReleaseWispTaskTest && \
DISPLAY=:7 \
HOME=/home/testUserForTone \
LANG=C \
LC_CTYPE=C.UTF-8 \
PATH=/bin:/usr/bin:/usr/sbin \
CLASSPATH=/tmp/tone/run/jtreg/jt-work/jdk_test/classes/40/com/alibaba/wisp2:/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp2:/tmp/tone/run/jtreg/jt-work/jdk_test/classes/40/lib/testlibrary:/tmp/tone/run/jtreg/jdk-repo/jdk/test/lib/testlibrary:/tmp/tone/run/jtreg/binary-download/jdk8u362-b740/lib/tools.jar:/tmp/tone/run/jtreg/jtreg/lib/javatest.jar:/tmp/tone/run/jtreg/jtreg/lib/jtreg.jar \
    /tmp/tone/run/jtreg/binary-download/jdk8u362-b740/bin/java \
        -Dtest.vm.opts='-Xcomp -XX:TieredStopAtLevel=1 -ea -esa' \
        -Dtest.tool.vm.opts='-J-Xcomp -J-XX:TieredStopAtLevel=1 -J-ea -J-esa' \
        -Dtest.compiler.opts= \
        -Dtest.java.opts= \
        -Dtest.jdk=/tmp/tone/run/jtreg/binary-download/jdk8u362-b740 \
        -Dcompile.jdk=/tmp/tone/run/jtreg/binary-download/jdk8u362-b740 \
        -Dtest.timeout.factor=4.0 \
        -Dtest.root=/tmp/tone/run/jtreg/jdk-repo/jdk/test \
        -Dtest.name=com/alibaba/wisp2/ReleaseWispTaskTest.java \
        -Dtest.file=/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp2/ReleaseWispTaskTest.java \
        -Dtest.src=/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp2 \
        -Dtest.src.path=/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp2:/tmp/tone/run/jtreg/jdk-repo/jdk/test/lib/testlibrary \
        -Dtest.classes=/tmp/tone/run/jtreg/jt-work/jdk_test/classes/40/com/alibaba/wisp2 \
        -Dtest.class.path=/tmp/tone/run/jtreg/jt-work/jdk_test/classes/40/com/alibaba/wisp2:/tmp/tone/run/jtreg/jt-work/jdk_test/classes/40/lib/testlibrary \
        -Xcomp \
        -XX:TieredStopAtLevel=1 \
        -ea \
        -esa \
        -XX:+UnlockExperimentalVMOptions \
        -XX:+UseWisp2 \
        -XX:ActiveProcessorCount=2 \
        com.sun.javatest.regtest.agent.MainWrapper /tmp/tone/run/jtreg/jt-work/jdk_test/com/alibaba/wisp2/ReleaseWispTaskTest.d/main.0.jta

TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Expected value to be true
```

**Comment by sendaoYan** [comment]
com/alibaba/wisp2/WispControlGroupPreemptTest.java

https://tone.aliyun-inc.com/ws/xesljfzh/test_result/156234?tab=2


```log
ACTION: main -- Failed. Execution failed: `main' threw exception: java.util.concurrent.ExecutionException: java.lang.RuntimeException: preempt doesn't happen in the wispTask container!!!
REASON: User specified action: run main/othervm -XX:+UnlockExperimentalVMOptions -XX:+UseWisp2 -Xcomp -Dcom.alibaba.wisp.carrierEngines=4 WispControlGroupPreemptTest 
TIME:   3.521 seconds
messages:
command: main -XX:+UnlockExperimentalVMOptions -XX:+UseWisp2 -Xcomp -Dcom.alibaba.wisp.carrierEngines=4 WispControlGroupPreemptTest
reason: User specified action: run main/othervm -XX:+UnlockExperimentalVMOptions -XX:+UseWisp2 -Xcomp -Dcom.alibaba.wisp.carrierEngines=4 WispControlGroupPreemptTest 
Mode: othervm [/othervm specified]
elapsed time (seconds): 3.521
configuration:
STDOUT:
STDERR:
java.util.concurrent.ExecutionException: java.lang.RuntimeException: preempt doesn't happen in the wispTask container!!!
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at WispControlGroupPreemptTest.main(WispControlGroupPreemptTest.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:855)
	at com.alibaba.wisp.engine.WispTask.runOutsideWisp(WispTask.java:299)
	at com.alibaba.wisp.engine.WispTask.runCommand(WispTask.java:274)
	at com.alibaba.wisp.engine.WispTask.access$100(WispTask.java:53)
	at com.alibaba.wisp.engine.WispTask$CacheableCoroutine.run(WispTask.java:241)
	at java.dyn.CoroutineBase.startInternal(CoroutineBase.java:62)
Caused by: java.lang.RuntimeException: preempt doesn't happen in the wispTask container!!!
	at jdk.testlibrary.Asserts.error(Asserts.java:438)
	at jdk.testlibrary.Asserts.assertTrue(Asserts.java:407)
	at WispControlGroupPreemptTest.lambda$getFutureTask$0(WispControlGroupPreemptTest.java:31)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.alibaba.wisp.engine.WispTask.runOutsideWisp(WispTask.java:299)
	at com.alibaba.wisp.engine.WispControlGroup.lambda$wrap$0(WispControlGroup.java:191)
	... 5 more

JavaTest Message: Test threw exception: java.util.concurrent.ExecutionException: java.lang.RuntimeException: preempt doesn't happen in the wispTask container!!!
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.util.concurrent.ExecutionException: java.lang.RuntimeException: preempt doesn't happen in the wispTask container!!!
rerun:
cd /tmp/tone/run/jtreg/jt-work/jdk_test/com/alibaba/wisp2/WispControlGroupPreemptTest && \
DISPLAY=:7 \
HOME=/root \
LANG=en_US.UTF-8 \
PATH=/bin:/usr/bin:/usr/sbin \
CLASSPATH=/tmp/tone/run/jtreg/jt-work/jdk_test/classes/98/com/alibaba/wisp2:/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp2:/tmp/tone/run/jtreg/jt-work/jdk_test/classes/98/lib/testlibrary:/tmp/tone/run/jtreg/jdk-repo/jdk/test/lib/testlibrary:/opt/java/openjdk/lib/tools.jar:/tmp/tone/run/jtreg/jtreg/lib/javatest.jar:/tmp/tone/run/jtreg/jtreg/lib/jtreg.jar \
    /opt/java/openjdk/bin/java \
        -Dtest.vm.opts='-Djdk.lang.processReaperUseDefaultStackSize=true -Xcomp -XX:TieredStopAtLevel=1 -ea -esa' \
        -Dtest.tool.vm.opts='-J-Djdk.lang.processReaperUseDefaultStackSize=true -J-Xcomp -J-XX:TieredStopAtLevel=1 -J-ea -J-esa' \
        -Dtest.compiler.opts= \
        -Dtest.java.opts= \
        -Dtest.jdk=/opt/java/openjdk \
        -Dcompile.jdk=/opt/java/openjdk \
        -Dtest.timeout.factor=4.0 \
        -Dtest.root=/tmp/tone/run/jtreg/jdk-repo/jdk/test \
        -Dtest.name=com/alibaba/wisp2/WispControlGroupPreemptTest.java \
        -Dtest.file=/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp2/WispControlGroupPreemptTest.java \
        -Dtest.src=/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp2 \
        -Dtest.src.path=/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp2:/tmp/tone/run/jtreg/jdk-repo/jdk/test/lib/testlibrary \
        -Dtest.classes=/tmp/tone/run/jtreg/jt-work/jdk_test/classes/98/com/alibaba/wisp2 \
        -Dtest.class.path=/tmp/tone/run/jtreg/jt-work/jdk_test/classes/98/com/alibaba/wisp2:/tmp/tone/run/jtreg/jt-work/jdk_test/classes/98/lib/testlibrary \
        -Djdk.lang.processReaperUseDefaultStackSize=true \
        -Xcomp \
        -XX:TieredStopAtLevel=1 \
        -ea \
        -esa \
        -XX:+UnlockExperimentalVMOptions \
        -XX:+UseWisp2 \
        -Xcomp \
        -Dcom.alibaba.wisp.carrierEngines=4 \
        com.sun.javatest.regtest.agent.MainWrapper /tmp/tone/run/jtreg/jt-work/jdk_test/com/alibaba/wisp2/WispControlGroupPreemptTest.d/main.0.jta
```
