### ISSUE TITLE
【上游问题】gc/survivorAlignment/TestPromotionToSurvivor.java随机失败

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell8#522]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/154088?tab=1

[jtreg-result-rerun.log](https://github.com/alibaba/dragonwell8/files/10939215/jtreg-result-rerun.log)

```log
ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Actual memory usage should not deviate from expected for more then 1048576
REASON: User specified action: run main/othervm -Xbootclasspath/a:. -XX:+UnlockDiagnosticVMOptions -XX:+WhiteBoxAPI -XX:NewSize=128m -XX:MaxNewSize=128m -XX:SurvivorRatio=1 -XX:+UnlockExperimentalVMOptions -XX:SurvivorAlignmentInBytes=32 -XX:OldSize=128m -XX:MaxHeapSize=256m -XX:-ExplicitGCInvokesConcurrent TestPromotionToSurvivor 10m 9 SURVIVOR 
TIME:   0.849 seconds
messages:
command: main -Xbootclasspath/a:. -XX:+UnlockDiagnosticVMOptions -XX:+WhiteBoxAPI -XX:NewSize=128m -XX:MaxNewSize=128m -XX:SurvivorRatio=1 -XX:+UnlockExperimentalVMOptions -XX:SurvivorAlignmentInBytes=32 -XX:OldSize=128m -XX:MaxHeapSize=256m -XX:-ExplicitGCInvokesConcurrent TestPromotionToSurvivor 10m 9 SURVIVOR
reason: User specified action: run main/othervm -Xbootclasspath/a:. -XX:+UnlockDiagnosticVMOptions -XX:+WhiteBoxAPI -XX:NewSize=128m -XX:MaxNewSize=128m -XX:SurvivorRatio=1 -XX:+UnlockExperimentalVMOptions -XX:SurvivorAlignmentInBytes=32 -XX:OldSize=128m -XX:MaxHeapSize=256m -XX:-ExplicitGCInvokesConcurrent TestPromotionToSurvivor 10m 9 SURVIVOR 
Mode: othervm [/othervm specified]
elapsed time (seconds): 0.849
configuration:
STDOUT:
SurvivorAlignmentTestMain info:
Desired object size: 16
Memory to fill: 10485760
Objects to be allocated: 655360
Alignment helpers to be used: 
For space EDEN:
AlignmentHelper for memory pool 'PS Eden Space':
Memory usage measurement precision: 8
Min object size in this space: 16
Object alignment in this space: 8

For space SURVIVOR:
AlignmentHelper for memory pool 'PS Survivor Space':
Memory usage measurement precision: 8
Min object size in this space: 16
Object alignment in this space: 32

For space TENURED:
AlignmentHelper for memory pool 'PS Old Gen':
Memory usage measurement precision: 8
Min object size in this space: 16
Object alignment in this space: 8


Verifying amount of memory allocated by threads:
Thread 28
baseline allocation: 4443952
current allocation:14932336
"MainThread" Id=28 RUNNABLE


Thread 4
baseline allocation: 0
current allocation:0
"Signal Dispatcher" Id=4 RUNNABLE


Thread 3
baseline allocation: 0
current allocation:0
"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@11dbf203


Thread 2
baseline allocation: 0
current allocation:0
"Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@1233121c


Thread 1
baseline allocation: 672184
current allocation:672184
"main" Id=1 WAITING on java.lang.Thread@72842def


Verifying memory usage in space: SURVIVOR
Allocated objects count: 655360
Desired object size: 16
Actual object size: 16
Expected object size in space: 32
Expected memory usage: 20971520
Actual memory usage: 22347776
Memory usage diff: 1376256
Max allowed usage diff: 1048576
STDERR:
java.lang.RuntimeException: Actual memory usage should not deviate from expected for more then 1048576
	at com.oracle.java.testlibrary.Asserts.error(Asserts.java:450)
	at com.oracle.java.testlibrary.Asserts.assertTrue(Asserts.java:377)
	at com.oracle.java.testlibrary.Asserts.assertLessThanOrEqual(Asserts.java:124)
	at com.oracle.java.testlibrary.Asserts.assertLTE(Asserts.java:102)
	at SurvivorAlignmentTestMain.verifyMemoryUsage(SurvivorAlignmentTestMain.java:333)
	at TestPromotionToSurvivor.main(TestPromotionToSurvivor.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:750)

JavaTest Message: Test threw exception: java.lang.RuntimeException: Actual memory usage should not deviate from expected for more then 1048576
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: Actual memory usage should not deviate from expected for more then 1048576
rerun:
cd /tmp/tone/run/jtreg/jt-work-rerun/gc/survivorAlignment/TestPromotionToSurvivor && \
DISPLAY=:7 \
HOME=/root \
LANG=en_US.UTF-8 \
PATH=/bin:/usr/bin:/usr/sbin \
CLASSPATH=/tmp/tone/run/jtreg/jt-work-rerun/classes/gc/survivorAlignment:/tmp/tone/run/jtreg/jdk-repo/hotspot/test/gc/survivorAlignment:/tmp/tone/run/jtreg/jt-work-rerun/classes/testlibrary:/tmp/tone/run/jtreg/jdk-repo/hotspot/test/testlibrary:/tmp/tone/run/jtreg/jt-work-rerun/classes/testlibrary/whitebox:/tmp/tone/run/jtreg/jdk-repo/hotspot/test/testlibrary/whitebox:/opt/java/openjdk/lib/tools.jar:/tmp/tone/run/jtreg/jtreg/lib/javatest.jar:/tmp/tone/run/jtreg/jtreg/lib/jtreg.jar \
    /opt/java/openjdk/bin/java \
        -Dtest.vm.opts='-Xmixed -ea -esa' \
        -Dtest.tool.vm.opts='-J-Xmixed -J-ea -J-esa' \
        -Dtest.compiler.opts= \
        -Dtest.java.opts= \
        -Dtest.jdk=/opt/java/openjdk \
        -Dcompile.jdk=/opt/java/openjdk \
        -Dtest.timeout.factor=4.0 \
        -Dtest.root=/tmp/tone/run/jtreg/jdk-repo/hotspot/test \
        -Dtest.name=gc/survivorAlignment/TestPromotionToSurvivor.java \
        -Dtest.file=/tmp/tone/run/jtreg/jdk-repo/hotspot/test/gc/survivorAlignment/TestPromotionToSurvivor.java \
        -Dtest.src=/tmp/tone/run/jtreg/jdk-repo/hotspot/test/gc/survivorAlignment \
        -Dtest.src.path=/tmp/tone/run/jtreg/jdk-repo/hotspot/test/gc/survivorAlignment:/tmp/tone/run/jtreg/jdk-repo/hotspot/test/testlibrary:/tmp/tone/run/jtreg/jdk-repo/hotspot/test/testlibrary/whitebox \
        -Dtest.classes=/tmp/tone/run/jtreg/jt-work-rerun/classes/gc/survivorAlignment \
        -Dtest.class.path=/tmp/tone/run/jtreg/jt-work-rerun/classes/gc/survivorAlignment:/tmp/tone/run/jtreg/jt-work-rerun/classes/testlibrary:/tmp/tone/run/jtreg/jt-work-rerun/classes/testlibrary/whitebox \
        -Xmixed \
        -ea \
        -esa \
        -Xbootclasspath/a:. \
        -XX:+UnlockDiagnosticVMOptions \
        -XX:+WhiteBoxAPI \
        -XX:NewSize=128m \
        -XX:MaxNewSize=128m \
        -XX:SurvivorRatio=1 \
        -XX:+UnlockExperimentalVMOptions \
        -XX:SurvivorAlignmentInBytes=32 \
        -XX:OldSize=128m \
        -XX:MaxHeapSize=256m \
        -XX:-ExplicitGCInvokesConcurrent \
        com.sun.javatest.regtest.agent.MainWrapper /tmp/tone/run/jtreg/jt-work-rerun/gc/survivorAlignment/TestPromotionToSurvivor.d/main.2.jta 10m 9 SURVIVOR
```

**Comment by sendaoYan** [comment]
sun/management/HotspotRuntimeMBean/GetSafepointSyncTime.java https://tone.aliyun-inc.com/ws/xesljfzh/test_result/154135 generic-all
