### ISSUE TITLE
【自研】multi-tenant/test/com/alibaba/tenant/TestHierachicalTenants.java随机失败 #509

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell8#524]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/154187?tab=2

```log
ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Total 1/3 testcases failed, class com.alibaba.tenant.TestHierachicalTenants
REASON: User specified action: run main/othervm/bootclasspath -XX:+MultiTenant -XX:+TenantCpuThrottling -Xmx200m -Xms200m com.alibaba.tenant.TestHierachicalTenants 
TIME:   40.435 seconds
messages:
command: main -XX:+MultiTenant -XX:+TenantCpuThrottling -Xmx200m -Xms200m com.alibaba.tenant.TestHierachicalTenants
reason: User specified action: run main/othervm/bootclasspath -XX:+MultiTenant -XX:+TenantCpuThrottling -Xmx200m -Xms200m com.alibaba.tenant.TestHierachicalTenants 
Mode: othervm [/othervm specified, /bootclasspath specified]
elapsed time (seconds): 40.435
configuration:
STDOUT:
=== Begin test com.alibaba.tenant.TestHierachicalTenants.testParentLimit ===
counts:
2507398
2499699
2551733
2509695
1963283
=== FAILED ( 0 passed, 1 failed3 total) ===
=== Begin test com.alibaba.tenant.TestHierachicalTenants.testParentBasic ===
=== PASSED (1 passed, 1 failed, 3 total) ===
=== Begin test com.alibaba.tenant.TestHierachicalTenants.testNullParent ===
=== PASSED (2 passed, 1 failed, 3 total) ===
STDERR:
=== Begin test com.alibaba.tenant.TestHierachicalTenants.testParentLimit ===
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at jdk.testlibrary.TestUtils.runWithPrefix(TestUtils.java:53)
	at com.alibaba.tenant.TestHierachicalTenants.main(TestHierachicalTenants.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:855)
Caused by: java.lang.RuntimeException: Expected that 2507398 < 1963283
	at jdk.testlibrary.Asserts.error(Asserts.java:438)
	at jdk.testlibrary.Asserts.assertTrue(Asserts.java:407)
	at jdk.testlibrary.Asserts.assertLessThan(Asserts.java:86)
	at jdk.testlibrary.Asserts.assertLessThan(Asserts.java:74)
	at com.alibaba.tenant.TestHierachicalTenants.testParentLimit(TestHierachicalTenants.java:137)
	... 12 more
=== FAILED ( 0 passed, 1 failed3 total) ===
=== Begin test com.alibaba.tenant.TestHierachicalTenants.testParentBasic ===
=== PASSED (1 passed, 1 failed, 3 total) ===
=== Begin test com.alibaba.tenant.TestHierachicalTenants.testNullParent ===
=== PASSED (2 passed, 1 failed, 3 total) ===
java.lang.RuntimeException: Total 1/3 testcases failed, class com.alibaba.tenant.TestHierachicalTenants
	at jdk.testlibrary.Asserts.error(Asserts.java:438)
	at jdk.testlibrary.Asserts.fail(Asserts.java:424)
	at jdk.testlibrary.TestUtils.runWithPrefix(TestUtils.java:67)
	at com.alibaba.tenant.TestHierachicalTenants.main(TestHierachicalTenants.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:855)

JavaTest Message: Test threw exception: java.lang.RuntimeException: Total 1/3 testcases failed, class com.alibaba.tenant.TestHierachicalTenants
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: Total 1/3 testcases failed, class com.alibaba.tenant.TestHierachicalTenants
rerun:
cd /tmp/tone/run/jtreg/jt-work/jdk_test/multi-tenant/test/com/alibaba/tenant/TestHierachicalTenants && \
DISPLAY=:7 \
HOME=/home/testUserForTone \
LANG=C \
LC_CTYPE=C.UTF-8 \
PATH=/bin:/usr/bin:/usr/sbin \
    /tmp/tone/run/jtreg/binary-download/dragonwell-8.14.15/bin/java \
        -Dtest.vm.opts='-Xmixed -ea -esa' \
        -Dtest.tool.vm.opts='-J-Xmixed -J-ea -J-esa' \
        -Dtest.compiler.opts= \
        -Dtest.java.opts= \
        -Dtest.jdk=/tmp/tone/run/jtreg/binary-download/dragonwell-8.14.15 \
        -Dcompile.jdk=/tmp/tone/run/jtreg/binary-download/dragonwell-8.14.15 \
        -Dtest.timeout.factor=4.0 \
        -Dtest.root=/tmp/tone/run/jtreg/jdk-repo/jdk/test \
        -Dtest.name=multi-tenant/test/com/alibaba/tenant/TestHierachicalTenants.java \
        -Dtest.file=/tmp/tone/run/jtreg/jdk-repo/jdk/test/multi-tenant/test/com/alibaba/tenant/TestHierachicalTenants.java \
        -Dtest.src=/tmp/tone/run/jtreg/jdk-repo/jdk/test/multi-tenant/test/com/alibaba/tenant \
        -Dtest.src.path=/tmp/tone/run/jtreg/jdk-repo/jdk/test/multi-tenant/test/com/alibaba/tenant:/tmp/tone/run/jtreg/jdk-repo/jdk/test/lib/testlibrary \
        -Dtest.classes=/tmp/tone/run/jtreg/jt-work/jdk_test/classes/104/multi-tenant/test/com/alibaba/tenant \
        -Dtest.class.path=/tmp/tone/run/jtreg/jt-work/jdk_test/classes/104/multi-tenant/test/com/alibaba/tenant:/tmp/tone/run/jtreg/jt-work/jdk_test/classes/104/lib/testlibrary \
        -Xbootclasspath/a:/tmp/tone/run/jtreg/jt-work/jdk_test/classes/104/multi-tenant/test/com/alibaba/tenant:/tmp/tone/run/jtreg/jdk-repo/jdk/test/multi-tenant/test/com/alibaba/tenant:/tmp/tone/run/jtreg/jt-work/jdk_test/classes/104/lib/testlibrary:/tmp/tone/run/jtreg/binary-download/dragonwell-8.14.15/lib/tools.jar:/tmp/tone/run/jtreg/jtreg/lib/javatest.jar:/tmp/tone/run/jtreg/jtreg/lib/jtreg.jar \
        -Xmixed \
        -ea \
        -esa \
        -XX:+MultiTenant \
        -XX:+TenantCpuThrottling \
        -Xmx200m \
        -Xms200m \
        com.sun.javatest.regtest.agent.MainWrapper /tmp/tone/run/jtreg/jt-work/jdk_test/multi-tenant/test/com/alibaba/tenant/TestHierachicalTenants.d/main.0.jta

TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: Total 1/3 testcases failed, class com.alibaba.tenant.TestHierachicalTenants
```

**Comment by sendaoYan** [comment]
multi-tenant/TestKillThread.java随机报NPE
