### ISSUE TITLE
【自研】com/alibaba/wisp/lock/UnsafeParkTest.java随机失败

### ISSUE THREAD

**Issue by sendaoYan** [alibaba/dragonwell8#526]
https://tone.aliyun-inc.com/ws/xesljfzh/test_result/154398?tab=1

```log
ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.RuntimeException: awake should be set before unsafe.park expired 1678458780757 1678458780299
REASON: User specified action: run main/othervm -XX:+UnlockExperimentalVMOptions -XX:+EnableCoroutine -Dcom.alibaba.wisp.transparentWispSwitch=true UnsafeParkTest 
TIME:   3.035 seconds
messages:
command: main -XX:+UnlockExperimentalVMOptions -XX:+EnableCoroutine -Dcom.alibaba.wisp.transparentWispSwitch=true UnsafeParkTest
reason: User specified action: run main/othervm -XX:+UnlockExperimentalVMOptions -XX:+EnableCoroutine -Dcom.alibaba.wisp.transparentWispSwitch=true UnsafeParkTest 
Mode: othervm [/othervm specified]
elapsed time (seconds): 3.035
configuration:
STDOUT:
STDERR:
java.lang.RuntimeException: awake should be set before unsafe.park expired 1678458780757 1678458780299
	at jdk.testlibrary.Asserts.error(Asserts.java:438)
	at jdk.testlibrary.Asserts.assertTrue(Asserts.java:407)
	at UnsafeParkTest.main(UnsafeParkTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:855)

JavaTest Message: Test threw exception: java.lang.RuntimeException: awake should be set before unsafe.park expired 1678458780757 1678458780299
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.RuntimeException: awake should be set before unsafe.park expired 1678458780757 1678458780299
rerun:
cd /tmp/tone/run/jtreg/jt-work/jdk_test/com/alibaba/wisp/lock/UnsafeParkTest && \
DISPLAY=:7 \
HOME=/root \
LANG=en_US.UTF-8 \
PATH=/bin:/usr/bin:/usr/sbin \
CLASSPATH=/tmp/tone/run/jtreg/jt-work/jdk_test/classes/101/com/alibaba/wisp/lock:/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp/lock:/tmp/tone/run/jtreg/jt-work/jdk_test/classes/101/lib/testlibrary:/tmp/tone/run/jtreg/jdk-repo/jdk/test/lib/testlibrary:/opt/java/openjdk/lib/tools.jar:/tmp/tone/run/jtreg/jtreg/lib/javatest.jar:/tmp/tone/run/jtreg/jtreg/lib/jtreg.jar \
    /opt/java/openjdk/bin/java \
        -Dtest.vm.opts='-Xcomp -ea -esa' \
        -Dtest.tool.vm.opts='-J-Xcomp -J-ea -J-esa' \
        -Dtest.compiler.opts= \
        -Dtest.java.opts= \
        -Dtest.jdk=/opt/java/openjdk \
        -Dcompile.jdk=/opt/java/openjdk \
        -Dtest.timeout.factor=4.0 \
        -Dtest.root=/tmp/tone/run/jtreg/jdk-repo/jdk/test \
        -Dtest.name=com/alibaba/wisp/lock/UnsafeParkTest.java \
        -Dtest.file=/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp/lock/UnsafeParkTest.java \
        -Dtest.src=/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp/lock \
        -Dtest.src.path=/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp/lock:/tmp/tone/run/jtreg/jdk-repo/jdk/test/lib/testlibrary \
        -Dtest.classes=/tmp/tone/run/jtreg/jt-work/jdk_test/classes/101/com/alibaba/wisp/lock \
        -Dtest.class.path=/tmp/tone/run/jtreg/jt-work/jdk_test/classes/101/com/alibaba/wisp/lock:/tmp/tone/run/jtreg/jt-work/jdk_test/classes/101/lib/testlibrary \
        -Xcomp \
        -ea \
        -esa \
        -XX:+UnlockExperimentalVMOptions \
        -XX:+EnableCoroutine \
        -Dcom.alibaba.wisp.transparentWispSwitch=true \
        com.sun.javatest.regtest.agent.MainWrapper /tmp/tone/run/jtreg/jt-work/jdk_test/com/alibaba/wisp/lock/UnsafeParkTest.d/main.0.jta
```

**Comment by sendaoYan** [comment]
com/alibaba/wisp/io/SocketTest.java 随机失败

https://tone.aliyun-inc.com/ws/xesljfzh/test_result/154912?tab=2


```log
ACTION: main -- Failed. Execution failed: `main' threw exception: java.lang.Error: not wake as expected
REASON: User specified action: run main/othervm -XX:+UnlockExperimentalVMOptions -XX:+EnableCoroutine -Dcom.alibaba.wisp.transparentWispSwitch=true SocketTest 
TIME:   1.453 seconds
messages:
command: main -XX:+UnlockExperimentalVMOptions -XX:+EnableCoroutine -Dcom.alibaba.wisp.transparentWispSwitch=true SocketTest
reason: User specified action: run main/othervm -XX:+UnlockExperimentalVMOptions -XX:+EnableCoroutine -Dcom.alibaba.wisp.transparentWispSwitch=true SocketTest 
Mode: othervm [/othervm specified]
elapsed time (seconds): 1.453
configuration:
STDOUT:
[Socket[addr=localhost/127.0.0.1,port=13000,localport=52030], Socket[addr=/127.0.0.1,port=52030,localport=13000]]
STDERR:
java.lang.Error: not wake as expected
	at SocketTest.testBlock(SocketTest.java:93)
	at SocketTest.main(SocketTest.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:82)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:879)

JavaTest Message: Test threw exception: java.lang.Error: not wake as expected
JavaTest Message: shutting down test

STATUS:Failed.`main' threw exception: java.lang.Error: not wake as expected
rerun:
cd /tmp/tone/run/jtreg/jt-work/jdk_test/com/alibaba/wisp/io/SocketTest && \
DISPLAY=:7 \
HOME=/home/testUserForTone \
LANG=C \
LC_CTYPE=C.UTF-8 \
PATH=/bin:/usr/bin:/usr/sbin \
CLASSPATH=/tmp/tone/run/jtreg/jt-work/jdk_test/classes/97/com/alibaba/wisp/io:/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp/io:/tmp/tone/run/jtreg/jt-work/jdk_test/classes/97/lib/testlibrary:/tmp/tone/run/jtreg/jdk-repo/jdk/test/lib/testlibrary:/tmp/tone/run/jtreg/binary-download/jdk8u362-b747/lib/tools.jar:/tmp/tone/run/jtreg/jtreg/lib/javatest.jar:/tmp/tone/run/jtreg/jtreg/lib/jtreg.jar \
    /tmp/tone/run/jtreg/binary-download/jdk8u362-b747/bin/java \
        -Dtest.vm.opts='-Xmixed -ea -esa' \
        -Dtest.tool.vm.opts='-J-Xmixed -J-ea -J-esa' \
        -Dtest.compiler.opts= \
        -Dtest.java.opts= \
        -Dtest.jdk=/tmp/tone/run/jtreg/binary-download/jdk8u362-b747 \
        -Dcompile.jdk=/tmp/tone/run/jtreg/binary-download/jdk8u362-b747 \
        -Dtest.timeout.factor=4.0 \
        -Dtest.root=/tmp/tone/run/jtreg/jdk-repo/jdk/test \
        -Dtest.name=com/alibaba/wisp/io/SocketTest.java \
        -Dtest.file=/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp/io/SocketTest.java \
        -Dtest.src=/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp/io \
        -Dtest.src.path=/tmp/tone/run/jtreg/jdk-repo/jdk/test/com/alibaba/wisp/io:/tmp/tone/run/jtreg/jdk-repo/jdk/test/lib/testlibrary \
        -Dtest.classes=/tmp/tone/run/jtreg/jt-work/jdk_test/classes/97/com/alibaba/wisp/io \
        -Dtest.class.path=/tmp/tone/run/jtreg/jt-work/jdk_test/classes/97/com/alibaba/wisp/io:/tmp/tone/run/jtreg/jt-work/jdk_test/classes/97/lib/testlibrary \
        -Xmixed \
        -ea \
        -esa \
        -XX:+UnlockExperimentalVMOptions \
        -XX:+EnableCoroutine \
        -Dcom.alibaba.wisp.transparentWispSwitch=true \
        com.sun.javatest.regtest.agent.MainWrapper /tmp/tone/run/jtreg/jt-work/jdk_test/com/alibaba/wisp/io/SocketTest.d/main.0.jta

TEST RESULT: Failed. Execution failed: `main' threw exception: java.lang.Error: not wake as expected
```
