### ISSUE TITLE
[Misc] Fix 8202353 patch ported before

### ISSUE THREAD

**Issue by zhengxiaolinX** [alibaba/dragonwell8#71]
**Description**
Port 8202353 from lastest jdk, in order to fix compatibility of 8u232 api change instead of origin openjdk8 patch.

**Steps to Reproduce**
run test jdk/jfr/event/os/TestSystemProcess.java by using `-XX:+EnableJFR` command:
```
java.lang.RuntimeException: No events
	at jdk.testlibrary.Asserts.error(Asserts.java:438)
	at jdk.testlibrary.Asserts.assertTrue(Asserts.java:407)
	at jdk.testlibrary.Asserts.assertFalse(Asserts.java:386)
	at jdk.testlibrary.jfr.Events.hasEvents(Events.java:155)
	at jdk.jfr.event.os.TestSystemProcess.main(TestSystemProcess.java:50)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:82)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javatest.regtest.agent.MainWrapper$MainThread.run(MainWrapper.java:127)
	at java.lang.Thread.run(Thread.java:860)
```
The `SystemProcessInterface::SystemProcesses::ProcessIterator::_event` in hotspot has no need to be allocated or deallocated, and it's not settled correctly. We'd fix it by porting patch from upstream.

**Expected behavior**
pass test jdk/jfr/event/os/TestSystemProcess.java

**JDK version**
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (Alibaba Dragonwell 8.2.2-b00) (build 1.8.0_232-b09)
OpenJDK 64-Bit Server VM (Alibaba Dragonwell 8.2.2-b00) (build 25.232-b09, mixed mode)

**Execution environment**
 - OS and version: Linux, x64
 - CPU model:
 - Number of CPU cores:
 - Size of physical memory:
 - Inside Linux container? No
   - Linux container name (docker, pouch, etc):
   - Linux container version:

**Comment by luchsh** [comment]
Could you please elaborate on what problem did you encounter? what has been done to fix it? 
and PLEASE USE THE ALIBABA ISSUE TEMPLATE!!!!!

**Comment by zhengxiaolinX** [comment]
> Could you please elaborate on what problem did you encounter? what has been done to fix it?
> and PLEASE USE THE ALIBABA ISSUE TEMPLATE!!!!!

Done.

**Comment by zhengxiaolinX** [comment]
Will merge two patches, close this issue first
