### ISSUE TITLE
[Bug] java.lang.UnsatisfiedLinkError: xxx\Alibaba_Dragonwell_8.2.2\j2sdk-image\jre\bin\fontmanager.dll

### ISSUE THREAD

**Issue by yangzhijie1488** [alibaba/dragonwell8#78]
**Description**
crash when run a java swing program in windows 10

**Steps to Reproduce**
1. crash when run a java swing program in windows 10

**Expected behavior**

**JDK version**
The output of `java -version` command
![image](https://user-images.githubusercontent.com/10305897/74585107-3a8b5800-5014-11ea-84a6-354cbf5260ea.png)

**Execution environment**
 - windows 10
![image](https://user-images.githubusercontent.com/10305897/74585112-4840dd80-5014-11ea-86bc-0879b14f2dea.png)

java.awt.HeadlessException
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.JFrame.<init>(JFrame.java:189)
	at com.leanwo.management.MainFrame.<init>(MainFrame.java:71)
	at com.leanwo.management.App$1.run(App.java:58)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "AWT-EventQueue-0" java.lang.UnsatisfiedLinkError: D:\ProgramFiles\Alibaba_Dragonwell_8.2.2\j2sdk-image\jre\bin\fontmanager.dll: %1 不是有效的 Win32 应用程序。
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1838)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at sun.font.FontManagerNativeLibrary$1.run(FontManagerNativeLibrary.java:61)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.FontManagerNativeLibrary.<clinit>(FontManagerNativeLibrary.java:32)
	at sun.font.SunFontManager$1.run(SunFontManager.java:339)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.SunFontManager.<clinit>(SunFontManager.java:335)
	at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:264)
	at sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1125)
	at javax.swing.JComponent.getFontMetrics(JComponent.java:1626)
	at javax.swing.plaf.basic.BasicGraphicsUtils.getPreferredButtonSize(BasicGraphicsUtils.java:276)
	at javax.swing.plaf.basic.BasicButtonUI.getPreferredSize(BasicButtonUI.java:376)
	at javax.swing.plaf.basic.BasicButtonUI.getMinimumSize(BasicButtonUI.java:366)
	at javax.swing.JComponent.getMinimumSize(JComponent.java:1744)
	at javax.swing.plaf.basic.BasicOptionPaneUI.addButtonComponents(BasicOptionPaneUI.java:693)
	at javax.swing.plaf.basic.BasicOptionPaneUI.createButtonArea(BasicOptionPaneUI.java:630)
	at javax.swing.plaf.basic.BasicOptionPaneUI.installComponents(BasicOptionPaneUI.java:178)
	at javax.swing.plaf.basic.BasicOptionPaneUI.installUI(BasicOptionPaneUI.java:141)
	at javax.swing.JComponent.setUI(JComponent.java:666)
	at javax.swing.JOptionPane.setUI(JOptionPane.java:1860)
	at javax.swing.JOptionPane.updateUI(JOptionPane.java:1882)
	at javax.swing.JOptionPane.<init>(JOptionPane.java:1845)
	at javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:857)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:666)
	at javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:637)
	at com.leanwo.management.App$1.run(App.java:66)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
####################内存信息####################
Heap Memory: init = 264241152(258048K) used = 72061544(70372K) committed = 255459328(249472K) max = 4132962304(4036096K)
Non Heap Memory: init = 2555904(2496K) used = 42307776(41316K) committed = 43659264(42636K) max = -1(-1K)
####################Gc信息####################
gc name=ParNew,gc count=2,gc time=25
gc name=ConcurrentMarkSweep,gc count=0,gc time=0
####################线程信息####################
blockcount=0,blocktime=-1,waitedcount=0,waitedtime=-1
"AWT-Shutdown" Id=28 RUNNABLE

blockcount=0,blocktime=-1,waitedcount=0,waitedtime=-1
"Thread-3" Id=24 RUNNABLE (in native)
	at sun.awt.windows.WToolkit.shutdown(Native Method)
	at sun.awt.windows.WToolkit$$Lambda$209/1103172110.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)
	...

blockcount=0,blocktime=-1,waitedcount=0,waitedtime=-1
"SpringContextShutdownHook" Id=19 RUNNABLE
	at java.lang.Class.isPrimitive(Native Method)
	at sun.invoke.util.Wrapper.forBasicType(Wrapper.java:296)
	at sun.invoke.util.BytecodeDescriptor.unparseSig(BytecodeDescriptor.java:126)
	at sun.invoke.util.BytecodeDescriptor.unparseMethod(BytecodeDescriptor.java:119)
	at sun.invoke.util.BytecodeDescriptor.unparse(BytecodeDescriptor.java:104)
	at java.lang.invoke.MethodType.toMethodDescriptorString(MethodType.java:1090)
	at java.lang.invoke.InnerClassLambdaMetafactory.generateConstructor(InnerClassLambdaMetafactory.java:355)
	at java.lang.invoke.InnerClassLambdaMetafactory.spinInnerClass(InnerClassLambdaMetafactory.java:279)
	at java.lang.invoke.InnerClassLambdaMetafactory.buildCallSite(InnerClassLambdaMetafactory.java:194)
	at java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:304)
	at java.lang.invoke.LambdaForm$DMH/208866101.invokeStatic_L6_L(LambdaForm$DMH)
	at java.lang.invoke.LambdaForm$BMH/1156210828.reinvoke(LambdaForm$BMH)
	at java.lang.invoke.LambdaForm$MH/989892772.invoke_MT(LambdaForm$MH)
	at java.lang.invoke.CallSite.makeSite(CallSite.java:302)
	at java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)
	at java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)
	at org.springframework.context.support.DefaultLifecycleProcessor.stopBeans(DefaultLifecycleProcessor.java:197)
	at org.springframework.context.support.DefaultLifecycleProcessor.onClose(DefaultLifecycleProcessor.java:128)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1021)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:948)
	...

blockcount=0,blocktime=-1,waitedcount=0,waitedtime=-1
"Thread-2" Id=20 RUNNABLE
	at sun.management.ThreadImpl.getThreadInfo1(Native Method)
	at sun.management.ThreadImpl.getThreadInfo(ThreadImpl.java:176)
	at sun.management.ThreadImpl.getThreadInfo(ThreadImpl.java:139)
	at com.leanwo.management.JvmExitMonit$1.run(JvmExitMonit.java:45)
	...

blockcount=0,blocktime=-1,waitedcount=1,waitedtime=-1
"Image Fetcher 0" Id=27 TIMED_WAITING on java.util.Vector@5cc61bde
	at java.lang.Object.wait(Native Method)
	-  waiting on java.util.Vector@5cc61bde
	at sun.awt.image.ImageFetcher.nextImage(ImageFetcher.java:147)
	-  waiting on java.util.Vector@5cc61bde
	at sun.awt.image.ImageFetcher.fetchloop(ImageFetcher.java:200)
	-  waiting on java.util.Vector@5cc61bde
	at sun.awt.image.ImageFetcher.run(ImageFetcher.java:169)
	-  waiting on java.util.Vector@5cc61bde
	...

blockcount=0,blocktime=-1,waitedcount=1,waitedtime=-1
"DestroyJavaVM" Id=26 WAITING on com.leanwo.management.JvmExitMonit$1@44de94c3
	at java.lang.Object.wait(Native Method)
	-  waiting on com.leanwo.management.JvmExitMonit$1@44de94c3
	at java.lang.Thread.join(Thread.java:1252)
	-  waiting on com.leanwo.management.JvmExitMonit$1@44de94c3
	at java.lang.Thread.join(Thread.java:1326)
	-  waiting on com.leanwo.management.JvmExitMonit$1@44de94c3
	at java.lang.ApplicationShutdownHooks.runHooks(ApplicationShutdownHooks.java:107)
	-  waiting on com.leanwo.management.JvmExitMonit$1@44de94c3
	at java.lang.ApplicationShutdownHooks$1.run(ApplicationShutdownHooks.java:46)
	-  waiting on com.leanwo.management.JvmExitMonit$1@44de94c3
	at java.lang.Shutdown.runHooks(Shutdown.java:123)
	-  waiting on com.leanwo.management.JvmExitMonit$1@44de94c3
	at java.lang.Shutdown.sequence(Shutdown.java:167)
	-  waiting on com.leanwo.management.JvmExitMonit$1@44de94c3
	at java.lang.Shutdown.shutdown(Shutdown.java:234)
	-  waiting on com.leanwo.management.JvmExitMonit$1@44de94c3
	...

blockcount=0,blocktime=-1,waitedcount=1,waitedtime=-1
"Java2D Disposer" Id=21 WAITING on java.lang.ref.ReferenceQueue$Lock@5201ee36
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@5201ee36
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@5201ee36
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@5201ee36
	at sun.java2d.Disposer.run(Disposer.java:148)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@5201ee36
	at java.lang.Thread.run(Thread.java:748)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@5201ee36
	...

blockcount=0,blocktime=-1,waitedcount=0,waitedtime=-1
"Attach Listener" Id=6 RUNNABLE

blockcount=0,blocktime=-1,waitedcount=0,waitedtime=-1
"Signal Dispatcher" Id=5 RUNNABLE

blockcount=185,blocktime=-1,waitedcount=4,waitedtime=-1
"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@563e70ae
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@563e70ae
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@563e70ae
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@563e70ae
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@563e70ae
	...

blockcount=3,blocktime=-1,waitedcount=3,waitedtime=-1
"Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@133ce40d
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.Reference$Lock@133ce40d
	at java.lang.Object.wait(Object.java:502)
	-  waiting on java.lang.ref.Reference$Lock@133ce40d
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	-  waiting on java.lang.ref.Reference$Lock@133ce40d
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)
	-  waiting on java.lang.ref.Reference$Lock@133ce40d
	...

**Comment by luchsh** [comment]
Thanks for reporting!
I quickly looked at the code where HealessException got thrown, it seems like JDK is running in headless mode.  Do you have a simple test case or program to help us to reproduce the issue?

**Comment by yangzhijie1488** [comment]
I add config 
System.setProperty("java.awt.headless", "false");
the problem fixed, but new problem exist.
**I try oracle jdk and open jdk, the following problem not show.**
Exception in thread "界面主线程" java.lang.NoClassDefFoundError: Could not initialize class sun.font.SunFontManager
	at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:264)
	at sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1125)
	at javax.swing.JComponent.getFontMetrics(JComponent.java:1626)
	at javax.swing.text.PlainView.calculateLongestLine(PlainView.java:639)
	at javax.swing.text.PlainView.updateMetrics(PlainView.java:209)
	at javax.swing.text.PlainView.setSize(PlainView.java:490)
	at javax.swing.plaf.basic.BasicTextUI$RootView.setSize(BasicTextUI.java:1722)
	at javax.swing.plaf.basic.BasicTextUI.getPreferredSize(BasicTextUI.java:917)
	at javax.swing.plaf.basic.BasicTextAreaUI.getPreferredSize(BasicTextAreaUI.java:120)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1662)
	at javax.swing.JTextArea.getPreferredSize(JTextArea.java:618)
	at javax.swing.text.JTextComponent.getPreferredScrollableViewportSize(JTextComponent.java:1937)
	at javax.swing.JTextArea.getPreferredScrollableViewportSize(JTextArea.java:695)
	at javax.swing.ViewportLayout.preferredLayoutSize(ViewportLayout.java:93)
	at java.awt.Container.preferredSize(Container.java:1799)
	at java.awt.Container.getPreferredSize(Container.java:1783)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at javax.swing.ScrollPaneLayout.preferredLayoutSize(ScrollPaneLayout.java:492)
	at java.awt.Container.preferredSize(Container.java:1799)
	at java.awt.Container.getPreferredSize(Container.java:1783)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
	at java.awt.Container.preferredSize(Container.java:1799)
	at java.awt.Container.getPreferredSize(Container.java:1783)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at java.awt.GridLayout.preferredLayoutSize(GridLayout.java:341)
	at java.awt.Container.preferredSize(Container.java:1799)
	at java.awt.Container.getPreferredSize(Container.java:1783)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at javax.swing.plaf.basic.BasicTabbedPaneUI$TabbedPaneLayout.calculateSize(BasicTabbedPaneUI.java:2304)
	at javax.swing.plaf.basic.BasicTabbedPaneUI$TabbedPaneLayout.preferredLayoutSize(BasicTabbedPaneUI.java:2278)
	at java.awt.Container.preferredSize(Container.java:1799)
	at java.awt.Container.getPreferredSize(Container.java:1783)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at java.awt.GridLayout.preferredLayoutSize(GridLayout.java:341)
	at java.awt.Container.preferredSize(Container.java:1799)
	at java.awt.Container.getPreferredSize(Container.java:1783)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
	at java.awt.Container.preferredSize(Container.java:1799)
	at java.awt.Container.getPreferredSize(Container.java:1783)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at javax.swing.JRootPane$RootLayout.preferredLayoutSize(JRootPane.java:920)
	at java.awt.Container.preferredSize(Container.java:1799)
	at java.awt.Container.getPreferredSize(Container.java:1783)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at java.awt.BorderLayout.preferredLayoutSize(BorderLayout.java:719)
	at java.awt.Container.preferredSize(Container.java:1799)
	at java.awt.Container.getPreferredSize(Container.java:1783)
	at java.awt.Window.pack(Window.java:809)
	at com.leanwo.management.App$1.run(App.java:63)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Exception in thread "界面主线程" java.lang.NoClassDefFoundError: Could not initialize class sun.font.SunFontManager
	at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:264)
	at sun.swing.SwingUtilities2.getFontMetrics(SwingUtilities2.java:1125)
	at javax.swing.JComponent.getFontMetrics(JComponent.java:1626)
	at javax.swing.plaf.basic.BasicGraphicsUtils.getPreferredButtonSize(BasicGraphicsUtils.java:276)
	at javax.swing.plaf.basic.BasicButtonUI.getPreferredSize(BasicButtonUI.java:376)
	at javax.swing.plaf.basic.BasicButtonUI.getMinimumSize(BasicButtonUI.java:366)
	at javax.swing.JComponent.getMinimumSize(JComponent.java:1744)
	at javax.swing.BoxLayout.checkRequests(BoxLayout.java:483)
	at javax.swing.BoxLayout.preferredLayoutSize(BoxLayout.java:301)
	at javax.swing.JToolBar$DefaultToolBarLayout.preferredLayoutSize(JToolBar.java:771)
	at java.awt.Container.preferredSize(Container.java:1799)
	at java.awt.Container.getPreferredSize(Container.java:1783)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1664)
	at java.awt.BorderLayout.layoutContainer(BorderLayout.java:815)
	at java.awt.Container.layout(Container.java:1513)
	at java.awt.Container.doLayout(Container.java:1502)
	at java.awt.Container.validateTree(Container.java:1698)
	at java.awt.Container.validateTree(Container.java:1707)
	at java.awt.Container.validateTree(Container.java:1707)
	at java.awt.Container.validateTree(Container.java:1707)
	at java.awt.Container.validate(Container.java:1633)
	at java.awt.Window.dispatchEventImpl(Window.java:2744)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by yangzhijie1488** [comment]
https://space.dingtalk.com/s/gwHOAM3XMQLOAuBslwPaACBhOWMzYTVlM2MxNmQ0NmQwOGVlMDAzNjdiYzY0ZGIyMA 
密码: kScn
extract zip, and execut run.bat. the problemn show.

**Comment by luchsh** [comment]
Thanks for the information, assigning this issue to zhengxiaolinX for further investigation.

**Comment by zhengxiaolinX** [comment]
Thank you for reporting this issue. We find a problem with our machine for building windows platform Dragonwell JDK. I've released a revision and tested with your application which currently works well. Could you please verify this build with your application? If there's no problem, we could further close this issue ;)
P.S. You can download it on [github](https://github.com/alibaba/dragonwell8/releases/download/v8.2.2-GA/Alibaba_Dragonwell_8.2.2-Experimental_Windows_x64.zip) or via [oss](https://dragonwell.oss-cn-shanghai.aliyuncs.com/8/x64/8.2.2-GA/Alibaba_Dragonwell_8.2.2-Experimental_Windows_x64.zip).
Looking forward to the result.

**Comment by yangzhijie1488** [comment]
@zhengxiaolinX @luchsh ,thanks very much, i update Dragonwell JDK, my program works fine.
thanks very much.
we support jdk from china.
