### ISSUE TITLE
CentOS8.1 NullPointerException FontConfiguration.getVersion

### ISSUE THREAD

**Issue by beming** [alibaba/dragonwell8#88]
OS: CentOS-8.1.1911-x86_64
Tomcat: tomcat9.0.31
JDK: Dragonwell 8.1.1/8.2.2
Else: had installed: fontconfig, dejavu-sans-fonts

java code (HttpServlet) :
@Override
	protected void doGet(HttpServletRequest request, HttpServletResponse response)
			throws ServletException, IOException {
		String sid = request.getSession().getId();
		LOGGER.debug("----------- session id 1111 ========= " + sid);
		// 清除缓存
		response.setHeader("Pragma", "No-cache");
		response.setHeader("Cache-Control", "no-cache");
		response.setDateHeader("Expires", 0L);
		// 显示类型
		response.setContentType("image/png");
		ConfigurableCaptchaService cs = new ConfigurableCaptchaService();
		OutputStream os = response.getOutputStream();

                 /*********** this  line throw exception:
		String patchca= EncoderHelper.getChallangeAndWriteImage(cs, "png", os);
		*************************/

		sid = SecurityUtils.getSubject().getSession().getId().toString();
		// 放入缓存
		Element element = new Element(sid, patchca);
		LOGGER.debug("----------- session id 1111222  ========= " + sid);
		cache.put(element);
		os.flush();
		os.close();
	}

error msg:

15:54:40.453 [http-nio-8080-exec-28] DEBUG o.a.shiro.web.servlet.AdviceFilter - Filter execution resulted in an unexpected Exception (not IOException or ServletException as the Filter API recommends).  Wrapping in ServletException and propagating.
15:54:40.463 [http-nio-8080-exec-28] ERROR 500.jsp - java.lang.NullPointerException
        at sun.awt.FontConfiguration.getVersion(FontConfiguration.java:1264)
        at sun.awt.FontConfiguration.readFontConfigFile(FontConfiguration.java:219)
        at sun.awt.FontConfiguration.init(FontConfiguration.java:107)
        at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:774)
        at sun.font.SunFontManager$2.run(SunFontManager.java:431)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.font.SunFontManager.<init>(SunFontManager.java:376)
        at sun.awt.FcFontManager.<init>(FcFontManager.java:35)
        at sun.awt.X11FontManager.<init>(X11FontManager.java:57)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
        at sun.font.SunFontManager.getInstance(SunFontManager.java:250)
        at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:264)
        at sun.java2d.SunGraphics2D.getFontMetrics(SunGraphics2D.java:863)
        at org.patchca.text.renderer.AbstractTextRenderer.convertToCharacters(AbstractTextRenderer.java:87)
        at org.patchca.text.renderer.AbstractTextRenderer.draw(AbstractTextRenderer.java:69)
        at org.patchca.service.AbstractCaptchaService.getCaptcha(AbstractCaptchaService.java:110)
        at org.patchca.utils.encoder.EncoderHelper.getChallangeAndWriteImage(EncoderHelper.java:32)

**Comment by luchsh** [comment]
Thanks for reporting, I saw similar issues allover the internet,
https://stackoverflow.com/questions/30626136/cannot-load-font-in-jre-8/50802170
https://github.com/AdoptOpenJDK/openjdk-docker/issues/75

Dragonwell 11 works well, so there might be certain patches to port.

**Comment by beming** [comment]
> Thanks for reporting, I saw similar issues allover the internet,
> https://stackoverflow.com/questions/30626136/cannot-load-font-in-jre-8/50802170
> [AdoptOpenJDK/openjdk-docker#75](https://github.com/AdoptOpenJDK/openjdk-docker/issues/75)
> 
> Dragonwell 11 works well, so there might be certain patches to port.

I had try the Dragonwell11, but does not working too.
I had try:
dnf install fontconfig
dnf install  dejavu-sans-fonts
and:
start the tomcat with: -Djava.awt.headless=true

all of above  can not work

**Comment by beming** [comment]
switch to OracleJDK，work well

**Comment by luchsh** [comment]
> > Thanks for reporting, I saw similar issues allover the internet,
> > https://stackoverflow.com/questions/30626136/cannot-load-font-in-jre-8/50802170
> > [AdoptOpenJDK/openjdk-docker#75](https://github.com/AdoptOpenJDK/openjdk-docker/issues/75)
> > Dragonwell 11 works well, so there might be certain patches to port.
> 
> I had try the Dragonwell11, but does not working too.
> I had try:
> dnf install fontconfig
> dnf install dejavu-sans-fonts
> and:
> start the tomcat with: -Djava.awt.headless=true
> 
> all of above can not work

Just FYI, I was testing with centos:8 docker image and the test case worked with Dragonwell 11 without error.
